// Corpus CIEGO 3 — escrito el 29-sep-2026 sin ver las reglas del anonimizador ni los otros corpus.
export default [
  // ───────────────────────── EXPEDIENTE: concurso de persona natural (Etxeberria) ─────────────────────────
  {
    id: 'e-concurso-solicitud',
    fuente: 'Solicitud de concurso de persona natural sin masa con exoneración del pasivo insatisfecho',
    clase: 'nativo',
    expediente: 'exp-concurso-etxeberria',
    texto: 'AL TRIBUNAL DE INSTANCIA DE BILBAO, SECCIÓN DE LO MERCANTIL, PLAZA N.º 1\n\nDoña Arantxa Olabarria Zubizarreta, Procuradora de los Tribunales, en nombre y representación de DON IÑAKI ETXEBERRIA GOIKOETXEA, mayor de edad, con DNI 48237165R y domicilio en la calle Hurtado de Amézqueta, 14, 3.º B, 48008 Bilbao, bajo la dirección letrada de don Gorka Bengoetxea Lasa, colegiado n.º 5.412 del Ilustre Colegio de la Abogacía de Bizkaia, ante el Tribunal comparezco y DIGO:\n\nQue por medio del presente escrito solicito la declaración de concurso de persona natural sin masa, al amparo del artículo 37 bis del Texto Refundido de la Ley Concursal, con solicitud de exoneración del pasivo insatisfecho.\n\nHECHOS\n\nPRIMERO.- Mi mandante fue trabajador autónomo en el sector de la hostelería hasta el cierre del bar «Goiko» en marzo de 2025. Desde entonces percibe el subsidio por desempleo, que se ingresa en la cuenta ES26 2100 0418 4802 0012 3456, de la que es cotitular junto a su esposa, doña Miren Arrieta Uriarte.\n\nSEGUNDO.- Desde 2024 el señor Etxeberria padece un trastorno de ansiedad generalizada con episodios de insomnio grave, extremo que se acredita con el informe médico del Centro de Salud de Deusto (documento n.º 4) y que le impidió reorientar su actividad.\n\nTERCERO.- El pasivo asciende a 187.430,55 euros, de los que 41.200 euros corresponden a la Agencia Estatal de Administración Tributaria y 12.870 euros a la Tesorería General de la Seguridad Social. El préstamo ICO de 60.000 euros fue avalado por su hermano, don Joseba Etxeberria Goikoetxea, con DNI 20916473C, a quien se comunicará la presente solicitud.\n\nCUARTO.- El deudor no ha sido condenado por delitos contra el patrimonio, contra el orden socioeconómico ni contra la Hacienda Pública en los diez años anteriores.\n\nTeléfono de contacto del deudor a efectos de notificaciones del administrador concursal: 688 41 27 90.',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE BILBAO, SECCIÓN DE LO MERCANTIL, PLAZA N.º 1'],
      ['PERSONA', 'Arantxa Olabarria Zubizarreta'],
      ['PERSONA', 'IÑAKI ETXEBERRIA GOIKOETXEA'],
      ['DNI', '48237165R'],
      ['DIRECCION', 'calle Hurtado de Amézqueta, 14, 3.º B, 48008 Bilbao'],
      ['PERSONA', 'Gorka Bengoetxea Lasa'],
      ['ORGANISMO', 'Ilustre Colegio de la Abogacía de Bizkaia'],
      ['NORMA', 'artículo 37 bis del Texto Refundido de la Ley Concursal'],
      ['IBAN', 'ES26 2100 0418 4802 0012 3456'],
      ['PERSONA', 'Miren Arrieta Uriarte'],
      ['PERSONA', 'Etxeberria'],
      ['CAT_ESPECIAL', 'trastorno de ansiedad generalizada con episodios de insomnio grave'],
      ['CAT_ESPECIAL', 'informe médico'],
      ['ORGANISMO', 'Centro de Salud de Deusto'],
      ['ORGANISMO', 'Agencia Estatal de Administración Tributaria'],
      ['ORGANISMO', 'Tesorería General de la Seguridad Social'],
      ['PERSONA', 'Joseba Etxeberria Goikoetxea'],
      ['DNI', '20916473C'],
      ['TELEFONO', '688 41 27 90'],
    ],
    ambiguo: ['Etxeberria'],
  },
  {
    id: 'e-concurso-informe-ac',
    fuente: 'Informe del administrador concursal sobre la buena fe del deudor',
    clase: 'nativo',
    expediente: 'exp-concurso-etxeberria',
    texto: 'INFORME DEL ADMINISTRADOR CONCURSAL (art. 37 ter TRLC)\n\nConcurso consecutivo 412/2026 — Tribunal de Instancia de Bilbao, Sección Mercantil, Plaza 1.\nDeudor: ETXEBERRIA GOIKOETXEA, Iñaki.\n\nQuien suscribe, Asier Ugalde Mendizabal, economista, designado administrador concursal, informa:\n\n1. Se han examinado los movimientos de la cuenta común con la esposa del concursado desde enero de 2023. No constan disposiciones injustificadas. Las transferencias mensuales de 300 euros a favor de doña Ane Etxeberria Arrieta, hija de ambos, estudiante en Donostia, obedecen a alimentos.\n\n2. El vehículo Seat León con matrícula 4821 KLM figura a nombre del concursado; su valor venal (1.900 euros) no justifica la liquidación.\n\n3. Consta en el Registro Central de Penados una condena de 2019 del hermano avalista por un delito de conducción bajo la influencia de bebidas alcohólicas, sin relevancia para la exoneración, puesto que afecta a un tercero. Respecto del propio Etxeberria no consta ninguna.\n\n4. Aunque el deudor atribuye el cierre del negocio a su enfermedad, el administrador aprecia que los ingresos ya caían desde 2022.\n\nConclusión: no se aprecian circunstancias que impidan la exoneración.\n\nEn Bilbao, a 3 de septiembre de 2026.\nAsier Ugalde Mendizabal — augalde.concursal@euskalnet.net — 944 23 18 06',
    oro: [
      ['AUTOS', 'Concurso consecutivo 412/2026'],
      ['ORGANO', 'Tribunal de Instancia de Bilbao, Sección Mercantil, Plaza 1'],
      ['PERSONA', 'ETXEBERRIA GOIKOETXEA, Iñaki'],
      ['PERSONA', 'Asier Ugalde Mendizabal'],
      ['PERSONA', 'Ane Etxeberria Arrieta'],
      ['MATRICULA', '4821 KLM'],
      ['ORGANISMO', 'Registro Central de Penados'],
      ['DATO_PENAL', 'una condena de 2019 del hermano avalista por un delito de conducción bajo la influencia de bebidas alcohólicas'],
      ['PERSONA', 'Etxeberria'],
      ['CORREO', 'augalde.concursal@euskalnet.net'],
      ['TELEFONO', '944 23 18 06'],
    ],
    ambiguo: ['Etxeberria'],
  },
  {
    id: 'e-concurso-auto-epi',
    fuente: 'Auto de concesión de la exoneración del pasivo insatisfecho',
    clase: 'nativo',
    expediente: 'exp-concurso-etxeberria',
    texto: 'TRIBUNAL DE INSTANCIA DE BILBAO\nSECCIÓN DE LO MERCANTIL — PLAZA N.º 1\nBILBOKO AURREKO AUZIALDIKO AUZITEGIA — MERKATARITZA ATALA\n\nConcurso consecutivo 412/2026\nNIG: 48.04.2-26/008812\n\nAUTO N.º 377/2026\n\nMagistrada: Itziar Aldekoa Urrutia\nEn Bilbao, a 22 de septiembre de 2026.\n\nANTECEDENTES DE HECHO\n\nPRIMERO.- La procuradora Sra. Olabarria, en representación de don Iñaki Etxeberria Goikoetxea, solicitó la exoneración del pasivo insatisfecho.\n\nSEGUNDO.- La Tesorería General de la Seguridad Social se opuso alegando que el deudor no había colaborado. Don Joseba Etxeberria, avalista, se personó sin formular oposición.\n\nFUNDAMENTOS DE DERECHO\n\nÚNICO.- Conforme al artículo 487 TRLC y a la STJUE de 11 de abril de 2024 (asunto C‑687/22, ECLI:EU:C:2024:311), el crédito público no puede quedar al margen de un examen individualizado. Etxeberria ha acreditado su buena fe.\n\nPARTE DISPOSITIVA\n\nSe concede a don Iñaki Etxeberria Goikoetxea la exoneración definitiva del pasivo insatisfecho, con la extensión señalada en el fundamento único.\n\nLo acuerda y firma la Magistrada, Itziar Aldekoa Urrutia. Doy fe.\nLa Letrada de la Administración de Justicia, Begoña Salcedo Ruiz.',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE BILBAO'],
      ['ORGANO', 'BILBOKO AURREKO AUZIALDIKO AUZITEGIA — MERKATARITZA ATALA'],
      ['AUTOS', 'Concurso consecutivo 412/2026'],
      ['PONENTE', 'Itziar Aldekoa Urrutia'],
      ['PERSONA', 'Olabarria'],
      ['PERSONA', 'Iñaki Etxeberria Goikoetxea'],
      ['ORGANISMO', 'Tesorería General de la Seguridad Social'],
      ['PERSONA', 'Joseba Etxeberria'],
      ['NORMA', 'artículo 487 TRLC'],
      ['NORMA', 'STJUE de 11 de abril de 2024'],
      ['ECLI', 'ECLI:EU:C:2024:311'],
      ['PERSONA', 'Etxeberria'],
      ['LAJ', 'Begoña Salcedo Ruiz'],
    ],
    ambiguo: ['Etxeberria'],
  },

  // ───────────────────────── EXPEDIENTE: violencia de género en Vigo (Parga) ─────────────────────────
  {
    id: 'e-vg-atestado',
    fuente: 'Atestado policial por violencia de género escaneado',
    clase: 'ocr',
    expediente: 'exp-vg-parga',
    texto: 'POLICIA NACIONAL - COMISARIA PROVINCIAL DE VIGO\nUNIDAD DE ATENCION A LA FAMILIA Y MUJER (UFAM)\nATESTADO N. 18.442/26\n\nEN VIGO, SIENDO LAS 02:40 HORAS DEL DIA 14 DE AGOSTO DE 2026, ANTE LOS FUNCIONARIOS CON CARNE PROFESIONAL 117.204 (INSTRUCTOR) Y 124.908 (SECRETARIO), COMPARECE:\n\nUXIA DOMINGUEZ PARGA, NACIDA EN LALIN, CON DNI 71439028Q, DOMICILIADA EN RUA DE COUTO SAN HONORATO 22 2 IZDA 36204 VIGO, TELEFONO 6 5 4 3 2 1 0 9 8 (SEGUN MANIFIESTA LO APUNTA ASI PORQUE SE LE BORRA LA AGENDA).\n\nMANIFIESTA: QUE HA MANTENIDO UNA RELACION SENTIMENTAL DE CUATRO ANOS CON BRAIS PARGA OUTEIRO, CON QUIEN NO CONVIVE DESDE JUNIO. QUE ESTA NOCHE PARGA SE HA PRESENTADO EN SU PORTAL Y LE HA DADO UN EMPUJON CONTRA EL BUZON, CAUSANDOLE UNA HERIDA EN LA CEJA IZQUIERDA. QUE ESTA EMBARAZADA DE ONCE SEMANAS Y TIENE MIEDO. QUE BRAIS YA ESTUVO EN PRISION EN 2021 POR UN ROBO CON VIOLENCIA. QUE SU VECINA DEL PRIMERO, ROSALIA FEIJOO CARIDE, OYO LOS GRITOS.\n\nSE ADJUNTA PARTE DE ASISTENCIA DEL HOSPITAL ALVARO CUNQUEIRO.\nVEHICULO DEL DENUNCIADO: 9034 HBD.',
    oro: [
      ['ORGANISMO', 'POLICIA NACIONAL - COMISARIA PROVINCIAL DE VIGO'],
      ['TIP', '117.204'],
      ['TIP', '124.908'],
      ['PERSONA', 'UXIA DOMINGUEZ PARGA'],
      ['DNI', '71439028Q'],
      ['DIRECCION', 'RUA DE COUTO SAN HONORATO 22 2 IZDA 36204 VIGO'],
      ['TELEFONO', '6 5 4 3 2 1 0 9 8'],
      ['PERSONA', 'BRAIS PARGA OUTEIRO'],
      ['PERSONA', 'PARGA'],
      ['CAT_ESPECIAL', 'UNA HERIDA EN LA CEJA IZQUIERDA'],
      ['CAT_ESPECIAL', 'EMBARAZADA DE ONCE SEMANAS'],
      ['PERSONA', 'BRAIS'],
      ['DATO_PENAL', 'YA ESTUVO EN PRISION EN 2021 POR UN ROBO CON VIOLENCIA'],
      ['PERSONA', 'ROSALIA FEIJOO CARIDE'],
      ['CAT_ESPECIAL', 'PARTE DE ASISTENCIA'],
      ['ORGANISMO', 'HOSPITAL ALVARO CUNQUEIRO'],
      ['MATRICULA', '9034 HBD'],
    ],
    ambiguo: ['PARGA'],
  },
  {
    id: 'e-vg-telegram',
    fuente: 'Mensajes de Telegram transcritos y aportados con la solicitud de orden de protección',
    clase: 'nativo',
    expediente: 'exp-vg-parga',
    texto: 'DOCUMENTO N.º 3 — TRANSCRIPCIÓN DE MENSAJES DE TELEGRAM (remitente con el número +34 633 90 12 47)\n\n[12/08/2026 23:14] Brais: Uxi abre\n[12/08/2026 23:15] Brais: se q estas con la Ro, no me mientas\n[12/08/2026 23:31] Uxía: Déjame en paz. Mañana voy a la médica, llevo dos días sin dormir y me han subido el lorazepam\n[12/08/2026 23:33] Brais: tu vas a flipar cuando tu primo Anxo se entere d lo q hacias\n[13/08/2026 00:02] Brais: ya sabes q no tengo nada q perder, ya estuve dentro\n[13/08/2026 00:05] Uxía: Voy a llamar a Rosalía y a la policía\n[13/08/2026 07:48] Anxo Domínguez: Uxi soy Anxo, me escribió tu ex, vente a casa con Iria y conmigo, rúa Ecuador 61, 4.º D\n\nSe aporta pantallazo con la sesión abierta en el teléfono 654 32 10 98 de la solicitante.',
    oro: [
      ['TELEFONO', '+34 633 90 12 47'],
      ['PERSONA', 'Brais'],
      ['PERSONA', 'Uxi'],
      ['PERSONA', 'Ro'],
      ['PERSONA', 'Uxía'],
      ['CAT_ESPECIAL', 'lorazepam'],
      ['PERSONA', 'Anxo'],
      ['DATO_PENAL', 'ya estuve dentro'],
      ['PERSONA', 'Rosalía'],
      ['PERSONA', 'Anxo Domínguez'],
      ['PERSONA', 'Iria'],
      ['DIRECCION', 'rúa Ecuador 61, 4.º D'],
      ['TELEFONO', '654 32 10 98'],
    ],
  },
  {
    id: 'e-vg-orden-proteccion',
    fuente: 'Auto de orden de protección (Tribunal de Instancia, sección de violencia sobre la mujer)',
    clase: 'nativo',
    expediente: 'exp-vg-parga',
    texto: 'TRIBUNAL DE INSTANCIA DE VIGO\nSECCIÓN DE VIOLENCIA SOBRE LA MUJER — PRAZA N.º 1\nTRIBUNAL DE INSTANCIA DE VIGO, SECCIÓN DE VIOLENCIA SOBRE A MULLER\n\nDiligencias urgentes (juicio rápido) 211/2026\n\nAUTO\n\nEn Vigo, a 14 de agosto de 2026.\n\nHECHOS\n\nÚNICO.- Por atestado de la Policía Nacional se ha tenido conocimiento de que Brais Parga Outeiro, con DNI 35602817J, habría agredido la madrugada de hoy a quien fue su pareja, Uxía Domínguez Parga. Doña Uxía se encuentra embarazada y ha sido asistida de una contusión periorbitaria con herida inciso-contusa de 2 cm.\n\nRAZONAMIENTOS JURÍDICOS\n\nPRIMERO.- Concurren los presupuestos del artículo 544 ter LECrim. Existen indicios de un delito del artículo 153.1 del Código Penal. La situación objetiva de riesgo resulta de los mensajes aportados, del temor expresado por la víctima, del testimonio de la vecina Sra. Feijoo y de que el investigado ya fue condenado en 2021, lo que valoro únicamente a efectos del riesgo.\n\nPARTE DISPOSITIVA\n\nSe acuerda la ORDEN DE PROTECCIÓN a favor de UXÍA DOMÍNGUEZ PARGA, prohibiendo a BRAIS PARGA OUTEIRO aproximarse a menos de 500 metros de su persona, de su domicilio en la rúa de Couto San Honorato, n.º 22, 2.º izquierda, y de su lugar de trabajo, así como comunicarse con ella por cualquier medio.\n\nAsí lo acorda, manda e asina Xoán Carlos Lamas Vilariño, xuíz. Dou fe.\nA Letrada da Administración de Xustiza, Marta Iglesias Porto.',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE VIGO\nSECCIÓN DE VIOLENCIA SOBRE LA MUJER — PRAZA N.º 1'],
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE VIGO, SECCIÓN DE VIOLENCIA SOBRE A MULLER'],
      ['AUTOS', 'Diligencias urgentes (juicio rápido) 211/2026'],
      ['ORGANISMO', 'Policía Nacional'],
      ['PERSONA', 'Brais Parga Outeiro'],
      ['DNI', '35602817J'],
      ['PERSONA', 'Uxía Domínguez Parga'],
      ['PERSONA', 'Uxía'],
      ['CAT_ESPECIAL', 'embarazada'],
      ['CAT_ESPECIAL', 'una contusión periorbitaria con herida inciso-contusa de 2 cm'],
      ['NORMA', 'artículo 544 ter LECrim'],
      ['NORMA', 'artículo 153.1 del Código Penal'],
      ['PERSONA', 'Feijoo'],
      ['DATO_PENAL', 'ya fue condenado en 2021'],
      ['PERSONA', 'UXÍA DOMÍNGUEZ PARGA'],
      ['PERSONA', 'BRAIS PARGA OUTEIRO'],
      ['DIRECCION', 'rúa de Couto San Honorato, n.º 22, 2.º izquierda'],
      ['PONENTE', 'Xoán Carlos Lamas Vilariño'],
      ['LAJ', 'Marta Iglesias Porto'],
    ],
  },
  {
    id: 'e-vg-escrito-defensa',
    fuente: 'Escrito de la defensa del investigado pidiendo la modificación de la orden de protección',
    clase: 'nativo',
    expediente: 'exp-vg-parga',
    texto: 'AL TRIBUNAL DE INSTANCIA DE VIGO, SECCIÓN DE VIOLENCIA SOBRE LA MUJER, PLAZA 1\nDiligencias urgentes 211/2026\n\nDon Óscar Rial Barreiro, abogado, en defensa de don Brais Parga Outeiro, DIGO:\n\n1. Que mi defendido trabaja como repartidor en la empresa Transportes Miño Sur, S.L., con domicilio social en la avenida de Madrid, 104, 36214 Vigo, cuyo almacén está a 380 metros del domicilio de la Sra. Domínguez.\n\n2. Que el Sr. Parga está en tratamiento en la Unidad de Conductas Adictivas de Vigo por dependencia de cocaína desde el 2 de septiembre, y aporta certificado de asistencia.\n\n3. Que Parga no tiene intención de acercarse a la denunciante y solicita que la distancia se reduzca a 300 metros, o que se le permita acceder al almacén en horario de 6:00 a 8:00.\n\nOTROSÍ DIGO que se cite como testigo a doña Iria Domínguez Parga, hermana de la denunciante, que puede declarar que las partes se vieron voluntariamente el 20 de julio.\n\nVigo, 2 de septiembre de 2026. Col. ICAVigo 3.118. Tel. despacho 986 43 72 15 · oscar.rial@rialabogados.gal',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE VIGO, SECCIÓN DE VIOLENCIA SOBRE LA MUJER, PLAZA 1'],
      ['AUTOS', 'Diligencias urgentes 211/2026'],
      ['PERSONA', 'Óscar Rial Barreiro'],
      ['PERSONA', 'Brais Parga Outeiro'],
      ['PERSONA', 'Domínguez'],
      ['PERSONA', 'Parga'],
      ['ORGANISMO', 'Unidad de Conductas Adictivas de Vigo'],
      ['CAT_ESPECIAL', 'dependencia de cocaína'],
      ['PERSONA', 'Iria Domínguez Parga'],
      ['TELEFONO', '986 43 72 15'],
      ['CORREO', 'oscar.rial@rialabogados.gal'],
    ],
    ambiguo: ['Domínguez', 'Parga'],
  },

  // ───────────────────────── EXPEDIENTE: accidente laboral (El Amrani) ─────────────────────────
  {
    id: 'e-al-acta-infraccion',
    fuente: 'Acta de infracción de la Inspección de Trabajo escaneada',
    clase: 'ocr',
    expediente: 'exp-accidente-elamrani',
    texto: 'MINISTERIO DE TRABAJO Y ECONOMIA SOCIAL\nINSPECCION PROVINCIAL DE TRABAJO Y SEGURIDAD SOCIAL DE ALMERIA\nACTA DE INFRACCION N. I042026000187342\n\nEMPRESA: INVERNADEROS CAMPOHERMOSO SL - CIF B84917327 - DOMICILIO SOCIAL: CTRA. DE NIJAR KM 7, 04110 CAMPOHERMOSO (ALMERIA)\nC.C.C.: 04/1234567/89\n\nHECHOS COMPROBADOS: EL 3 DE MARZO DE 2026 EL TRABAJADOR MOHAMED EL AMRANI BOUZID, NIE X4127893Z, N. AFILIACION 28/1045673272, CAYO DESDE UNA ALTURA DE 4,20 METROS AL CEDER UNA PLACA DE POLICARBONATO DE LA CUBIERTA DEL INVERNADERO N. 6, SIN QUE EXISTIERA LINEA DE VIDA NI ARNES. SUFRIO FRACTURA-ESTALLIDO DE LA VERTEBRA L1 CON PARAPARESIA. EL ENCARGADO, FRANCISCO JAVIER MARTOS LUNA, RECONOCIO QUE EL ARNES ESTABA EN EL ALMACEN. SU HERMANO YOUSSEF EL AMRANI, QUE TRABAJABA EN LA MISMA NAVE, PRESENCIO LA CAIDA.\n\nCALIFICACION: FALTA MUY GRAVE, ART. 13.10 LISOS.\nPROPUESTA DE SANCION: 187.515 EUROS.\nSE PROPONE RECARGO DE PRESTACIONES DEL 40 %.\n\nEL INSPECTOR DE TRABAJO Y SEGURIDAD SOCIAL: RAFAEL SORIA CAZORLA',
    oro: [
      ['ORGANISMO', 'MINISTERIO DE TRABAJO Y ECONOMIA SOCIAL'],
      ['ORGANISMO', 'INSPECCION PROVINCIAL DE TRABAJO Y SEGURIDAD SOCIAL DE ALMERIA'],
      ['AUTOS', 'I042026000187342'],
      ['CIF', 'B84917327'],
      ['PERSONA', 'MOHAMED EL AMRANI BOUZID'],
      ['NIE', 'X4127893Z'],
      ['NUSS', '28/1045673272'],
      ['CAT_ESPECIAL', 'FRACTURA-ESTALLIDO DE LA VERTEBRA L1 CON PARAPARESIA'],
      ['PERSONA', 'FRANCISCO JAVIER MARTOS LUNA'],
      ['PERSONA', 'YOUSSEF EL AMRANI'],
      ['NORMA', 'ART. 13.10 LISOS'],
      ['PERSONA', 'RAFAEL SORIA CAZORLA'],
    ],
  },
  {
    id: 'e-al-demanda',
    fuente: 'Demanda de accidente de trabajo: recargo e indemnización de daños',
    clase: 'nativo',
    expediente: 'exp-accidente-elamrani',
    texto: 'AL TRIBUNAL DE INSTANCIA DE ALMERÍA, SECCIÓN DE LO SOCIAL, PLAZA N.º 3 QUE POR TURNO CORRESPONDA\n\nDoña Fatima Zahra Benali Haddou, abogada del Ilustre Colegio de Abogados de Almería, en nombre de DON MOHAMED EL AMRANI BOUZID, con NIE X4127893Z y domicilio en calle Carretera de Ronda, 188, bloque 2, 5.º A, 04005 Almería, teléfono 0034 642 118 305, formula DEMANDA en reclamación de indemnización de daños y perjuicios derivados de accidente de trabajo contra INVERNADEROS CAMPOHERMOSO, S.L. (B84917327) y su aseguradora.\n\nHECHOS\n\nPRIMERO.- El actor presta servicios como peón agrícola desde 2019.\n\nSEGUNDO.- El 3 de marzo de 2026 sufrió el accidente descrito en el acta de la Inspección. Fue intervenido en el Hospital Universitario Torrecárdenas mediante artrodesis T12-L2. Permaneció hospitalizado 38 días y desde entonces arrastra paraparesia de miembros inferiores y vejiga neurógena, y ha sido diagnosticado de trastorno de estrés postraumático.\n\nTERCERO.- El INSS le ha reconocido una incapacidad permanente absoluta por resolución de 30 de junio de 2026, que no es objeto de este pleito. Se reclama la indemnización conforme al baremo de tráfico aplicado orientativamente (STS 4.ª de 23 de marzo de 2015, rcud 2057/2014).\n\nCUARTO.- El Sr. El Amrani es musulmán practicante y ha dejado de poder acudir a la mezquita de La Chanca, lo que agrava el perjuicio moral por pérdida de actividades.\n\nQUINTO.- Testigos: don Youssef El Amrani Bouzid y don Francisco Javier Martos Luna, encargado.\n\nPor lo expuesto, SUPLICO se dicte sentencia condenando a las demandadas a abonar 412.980,40 euros.',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE ALMERÍA, SECCIÓN DE LO SOCIAL, PLAZA N.º 3'],
      ['PERSONA', 'Fatima Zahra Benali Haddou'],
      ['ORGANISMO', 'Ilustre Colegio de Abogados de Almería'],
      ['PERSONA', 'MOHAMED EL AMRANI BOUZID'],
      ['NIE', 'X4127893Z'],
      ['DIRECCION', 'calle Carretera de Ronda, 188, bloque 2, 5.º A, 04005 Almería'],
      ['TELEFONO', '0034 642 118 305'],
      ['CIF', 'B84917327'],
      ['ORGANISMO', 'Hospital Universitario Torrecárdenas'],
      ['CAT_ESPECIAL', 'artrodesis T12-L2'],
      ['CAT_ESPECIAL', 'hospitalizado 38 días'],
      ['CAT_ESPECIAL', 'paraparesia de miembros inferiores y vejiga neurógena'],
      ['CAT_ESPECIAL', 'trastorno de estrés postraumático'],
      ['ORGANISMO', 'INSS'],
      ['CAT_ESPECIAL', 'incapacidad permanente absoluta'],
      ['NORMA', 'STS 4.ª de 23 de marzo de 2015'],
      ['AUTOS', 'rcud 2057/2014'],
      ['PERSONA', 'El Amrani'],
      ['CAT_ESPECIAL', 'musulmán practicante'],
      ['CAT_ESPECIAL', 'acudir a la mezquita de La Chanca'],
      ['PERSONA', 'Youssef El Amrani Bouzid'],
      ['PERSONA', 'Francisco Javier Martos Luna'],
    ],
    ambiguo: ['El Amrani'],
  },
  {
    id: 'e-al-evi',
    fuente: 'Dictamen-propuesta del Equipo de Valoración de Incapacidades',
    clase: 'nativo',
    expediente: 'exp-accidente-elamrani',
    texto: 'INSTITUTO NACIONAL DE LA SEGURIDAD SOCIAL\nDirección Provincial de Almería — Equipo de Valoración de Incapacidades\n\nDICTAMEN-PROPUESTA\nExpediente IP 04/2026/004518\n\nApellidos y nombre: EL AMRANI BOUZID, MOHAMED\nNIE: X4127893Z — NAF: 28/1045673272\nProfesión habitual: peón agrícola\nContingencia: accidente de trabajo\n\nCUADRO CLÍNICO RESIDUAL: fractura-estallido L1 intervenida; paraparesia ASIA D; vejiga neurógena con autosondaje intermitente; trastorno adaptativo mixto.\n\nLIMITACIONES ORIENTADORAS: marcha con dos bastones ingleses; imposibilidad de bipedestación prolongada y de cargas.\n\nPROPUESTA: INCAPACIDAD PERMANENTE ABSOLUTA para todo trabajo, derivada de accidente de trabajo. Revisable por agravación o mejoría a partir del 30/06/2028.\n\nFacultativa ponente del EVI: Dra. Encarnación Gádor Rubio. Presidente del EVI: Manuel Aguilera Moya.',
    oro: [
      ['ORGANISMO', 'INSTITUTO NACIONAL DE LA SEGURIDAD SOCIAL'],
      ['AUTOS', 'Expediente IP 04/2026/004518'],
      ['PERSONA', 'EL AMRANI BOUZID, MOHAMED'],
      ['NIE', 'X4127893Z'],
      ['NUSS', '28/1045673272'],
      ['CAT_ESPECIAL', 'fractura-estallido L1 intervenida; paraparesia ASIA D; vejiga neurógena con autosondaje intermitente; trastorno adaptativo mixto'],
      ['CAT_ESPECIAL', 'marcha con dos bastones ingleses; imposibilidad de bipedestación prolongada y de cargas'],
      ['OBJETO', 'INCAPACIDAD PERMANENTE ABSOLUTA'],
      ['PERSONA', 'Encarnación Gádor Rubio'],
      ['PERSONA', 'Manuel Aguilera Moya'],
    ],
  },
  {
    id: 'e-al-suplicacion',
    fuente: 'Recurso de suplicación de la empresa contra la sentencia de recargo',
    clase: 'nativo',
    expediente: 'exp-accidente-elamrani',
    texto: 'A LA SALA DE LO SOCIAL DEL TRIBUNAL SUPERIOR DE JUSTICIA DE ANDALUCÍA, CON SEDE EN GRANADA\n\nRecurso de suplicación contra la sentencia n.º 244/2026 del Tribunal de Instancia de Almería, Sección Social, Plaza 3, autos 318/2026.\n\nDon Alfonso Ibáñez de Aldecoa y Gil de Santivañes, letrado, en nombre de INVERNADEROS CAMPOHERMOSO, S.L., formaliza RECURSO DE SUPLICACIÓN al amparo del artículo 193 b) y c) LRJS.\n\nMOTIVO PRIMERO (revisión de hechos probados).- Debe suprimirse del hecho probado cuarto la frase «el trabajador no había recibido formación preventiva», pues al folio 212 consta el certificado de formación firmado por Mohamed.\n\nMOTIVO SEGUNDO.- El hermano del actor, Youssef, reconoció en el acto del juicio que Mohamed se había quitado el arnés para subir a la cubierta. La sentencia no valora que el propio El Amrani había sido amonestado por ello en 2025. Tampoco valora que el testigo Martos Luna estuvo de baja por depresión durante el mes anterior y no pudo supervisar.\n\nMOTIVO TERCERO.- Infracción del artículo 164 LGSS y de la doctrina de la STS 4.ª 480/2023, de 5 de julio (ECLI:ES:TS:2023:3120).\n\nGranada, 15 de septiembre de 2026.',
    oro: [
      ['ORGANO', 'SALA DE LO SOCIAL DEL TRIBUNAL SUPERIOR DE JUSTICIA DE ANDALUCÍA, CON SEDE EN GRANADA'],
      ['NORMA', 'sentencia n.º 244/2026'],
      ['ORGANO', 'Tribunal de Instancia de Almería, Sección Social, Plaza 3'],
      ['AUTOS', 'autos 318/2026'],
      ['PERSONA', 'Alfonso Ibáñez de Aldecoa y Gil de Santivañes'],
      ['NORMA', 'artículo 193 b) y c) LRJS'],
      ['PERSONA', 'Mohamed'],
      ['PERSONA', 'Youssef'],
      ['PERSONA', 'El Amrani'],
      ['PERSONA', 'Martos Luna'],
      ['CAT_ESPECIAL', 'de baja por depresión'],
      ['NORMA', 'artículo 164 LGSS'],
      ['NORMA', 'STS 4.ª 480/2023, de 5 de julio'],
      ['ECLI', 'ECLI:ES:TS:2023:3120'],
    ],
    ambiguo: ['El Amrani'],
  },

  // ───────────────────────── EXPEDIENTE: acoso escolar en Girona (Font) ─────────────────────────
  {
    id: 'e-esc-expedient-disciplinari',
    fuente: 'Resolución de expediente disciplinario de un alumno de ESO (institut catalán)',
    clase: 'nativo',
    expediente: 'exp-escolar-font',
    texto: 'INSTITUT MONTILIVI — GIRONA\nDepartament d\'Educació i Formació Professional\n\nRESOLUCIÓ DE L\'EXPEDIENT DISCIPLINARI 3/2025-26\n\nAlumne expedientat: Pau Font Vidal, 3r d\'ESO B, nascut el 2011.\nPares: Jordi Font i Casals i Montserrat Vidal Puig, amb domicili al carrer de la Rutlla, 57, 1r 2a, 17002 Girona.\nInstructora: Laia Bosch Serrat, professora de matemàtiques.\n\nFETS PROVATS\n1. Entre octubre i desembre de 2025, l\'alumne Pau Font, juntament amb un altre alumne no identificat, va penjar en un grup de WhatsApp de la classe fotografies de l\'alumne Arnau Soler Bassols amb comentaris sobre la seva orientació sexual i el va anomenar «maricó» en diverses ocasions.\n2. L\'Arnau segueix tractament psicològic al CSMIJ del Gironès per una simptomatologia ansiosa-depressiva reactiva.\n3. En Pau va reconèixer els fets en l\'audiència. La seva mare va manifestar que el noi té un TDAH diagnosticat i pren metilfenidat.\n\nRESOLC: suspensió del dret d\'assistència al centre durant 15 dies lectius, conforme a l\'article 37.3 de la Llei 12/2009, del 10 de juliol, d\'educació.\n\nLa directora, Núria Pagès Estany. Girona, 20 de gener de 2026.',
    oro: [
      ['ORGANISMO', 'INSTITUT MONTILIVI'],
      ['ORGANISMO', 'Departament d\'Educació i Formació Professional'],
      ['AUTOS', 'EXPEDIENT DISCIPLINARI 3/2025-26'],
      ['PERSONA', 'Pau Font Vidal'],
      ['PERSONA', 'Jordi Font i Casals'],
      ['PERSONA', 'Montserrat Vidal Puig'],
      ['DIRECCION', 'carrer de la Rutlla, 57, 1r 2a, 17002 Girona'],
      ['PERSONA', 'Laia Bosch Serrat'],
      ['PERSONA', 'Pau Font'],
      ['PERSONA', 'Arnau Soler Bassols'],
      ['CAT_ESPECIAL', 'orientació sexual'],
      ['PERSONA', 'Arnau'],
      ['CAT_ESPECIAL', 'tractament psicològic'],
      ['ORGANISMO', 'CSMIJ del Gironès'],
      ['CAT_ESPECIAL', 'simptomatologia ansiosa-depressiva reactiva'],
      ['PERSONA', 'Pau'],
      ['CAT_ESPECIAL', 'TDAH'],
      ['CAT_ESPECIAL', 'metilfenidat'],
      ['NORMA', 'article 37.3 de la Llei 12/2009, del 10 de juliol, d\'educació'],
      ['PERSONA', 'Núria Pagès Estany'],
    ],
  },
  {
    id: 'e-esc-serveis-socials',
    fuente: 'Informe de los servicios sociales municipales sobre la familia del menor expedientado',
    clase: 'nativo',
    expediente: 'exp-escolar-font',
    texto: 'AJUNTAMENT DE GIRONA — ÀREA DE DRETS SOCIALS\nEquip Bàsic d\'Atenció Social (EBAS) Est\nINFORME SOCIAL — Exp. SS-2026/1184\n\nPersona de referència: VIDAL PUIG, Montserrat (DNI 11873492H), tel. 972 20 45 61 / 699 031 552.\nUnitat de convivència: la mare, el fill Pau (14 anys) i la germana petita, Martina Font Vidal (8 anys). El pare, Jordi Font, viu a Salt i veu els fills cap de setmana alterns.\n\nValoració: la Sra. Vidal treballa de cuidadora amb contracte parcial. Refereix que el Sr. Font té problemes amb l\'alcohol des de fa anys i que va estar ingressat a la unitat de desintoxicació de l\'Hospital Santa Caterina el 2023. La família percep la Renda Garantida de Ciutadania. La Martina té reconeguda una discapacitat del 45 % per una hipoacúsia bilateral.\n\nLa família d\'Arnau (mare: Teresa Bassols Coll) ha demanat mediació. Font (pare) no ha respost a les trucades.\n\nTreballadora social: Gemma Riera Oliveras, col. 4.021.',
    oro: [
      ['ORGANISMO', 'AJUNTAMENT DE GIRONA'],
      ['AUTOS', 'Exp. SS-2026/1184'],
      ['PERSONA', 'VIDAL PUIG, Montserrat'],
      ['DNI', '11873492H'],
      ['TELEFONO', '972 20 45 61'],
      ['TELEFONO', '699 031 552'],
      ['PERSONA', 'Pau'],
      ['PERSONA', 'Martina Font Vidal'],
      ['PERSONA', 'Jordi Font'],
      ['PERSONA', 'Vidal'],
      ['PERSONA', 'Font'],
      ['CAT_ESPECIAL', 'problemes amb l\'alcohol'],
      ['CAT_ESPECIAL', 'ingressat a la unitat de desintoxicació'],
      ['ORGANISMO', 'Hospital Santa Caterina'],
      ['PERSONA', 'Martina'],
      ['CAT_ESPECIAL', 'discapacitat del 45 %'],
      ['CAT_ESPECIAL', 'hipoacúsia bilateral'],
      ['PERSONA', 'Arnau'],
      ['PERSONA', 'Teresa Bassols Coll'],
      ['PERSONA', 'Gemma Riera Oliveras'],
    ],
    ambiguo: ['Font'],
  },
  {
    id: 'e-esc-fiscal-menors',
    fuente: 'Escrito de alegaciones del Ministerio Fiscal en expediente de reforma de menores',
    clase: 'nativo',
    expediente: 'exp-escolar-font',
    texto: 'FISCALIA PROVINCIAL DE GIRONA — SECCIÓ DE MENORS\nExpedient de reforma 88/2026\nTRIBUNAL D\'INSTÀNCIA DE GIRONA, SECCIÓ DE MENORS\n\nEL FISCAL, en l\'expedient de referència, formula ESCRIT D\'AL·LEGACIONS contra el menor P.F.V., nascut el 2011, fill de Jordi i de Montserrat:\n\nPRIMERA.- Fets: el menor, en connivència amb Hugo Esteban Cano, de 15 anys, va difondre imatges d\'un company i el va insultar per la seva orientació sexual de forma reiterada. La víctima, A.S.B., va patir un episodi d\'autolesions el gener de 2026 que va requerir atenció a urgències.\nSEGONA.- Qualificació: delicte contra la integritat moral (art. 173.1 CP) i delicte d\'odi (art. 510.2.a CP).\nTERCERA.- Circumstàncies: cap. El menor no té antecedents a la Fiscalia de Menors; l\'altre menor sí, per un furt del 2025.\nQUARTA.- Mesura: 8 mesos de llibertat vigilada amb obligació de seguir un programa formatiu d\'educació en la diversitat, i 50 hores de prestacions en benefici de la comunitat.\n\nProves: declaració de la víctima, de la seva mare, Sra. Bassols, i de la tutora Laia Bosch.\n\nGirona, 12 de maig de 2026. La fiscal, Anna Mercader Vila.',
    oro: [
      ['ORGANISMO', 'FISCALIA PROVINCIAL DE GIRONA'],
      ['AUTOS', 'Expedient de reforma 88/2026'],
      ['ORGANO', 'TRIBUNAL D\'INSTÀNCIA DE GIRONA, SECCIÓ DE MENORS'],
      ['PERSONA', 'P.F.V.'],
      ['PERSONA', 'Jordi'],
      ['PERSONA', 'Montserrat'],
      ['PERSONA', 'Hugo Esteban Cano'],
      ['CAT_ESPECIAL', 'orientació sexual'],
      ['PERSONA', 'A.S.B.'],
      ['CAT_ESPECIAL', 'un episodi d\'autolesions'],
      ['NORMA', 'art. 173.1 CP'],
      ['NORMA', 'art. 510.2.a CP'],
      // El dato es el delito, no «l'altre menor sí» (29-sep).
      ['DATO_PENAL', 'per un furt del 2025'],
      ['PERSONA', 'Bassols'],
      ['PERSONA', 'Laia Bosch'],
      ['PERSONA', 'Anna Mercader Vila'],
    ],
  },

  // ───────────────────────── EXPEDIENTE: prisión provisional en Palma (Dumitrescu) ─────────────────────────
  {
    id: 'e-dum-correo-esposa',
    fuente: 'Correo de la esposa de un detenido al despacho, de madrugada',
    clase: 'correo',
    expediente: 'exp-dumitrescu',
    texto: 'De: Mihaela Dumitrescu <mihaela.dumi84@yahoo.es>\nPara: guardia@bonetadvocats.com\nFecha: sábado, 6 de junio de 2026, 03:12\nAsunto: URGENTE detenido mi marido Florin\n\nBuenas noches, perdonen la hora. Me dio su correo mi vecina Carmen. A Florin lo han detenido esta tarde en el puerto de Alcúdia la Guardia Civil, dicen que por algo de un camión con tabaco. Está en el cuartel de Inca. Él ya tiene antecedentes por conducir sin carnet de 2022 y tengo miedo que por eso no le suelten.\n\nEs muy importante que sepan que Florin toma metadona todos los días en el CAD de Manacor y si no se la dan se pone muy mal. También es diabético.\n\nMi teléfono es el 671.09.43.28 y el de su hermano Costel el 0040 744 512 309 (está en Rumanía). Vivimos en Camí de Son Fangos, 14, 1.º, 07500 Manacor.\n\nMi NIE Y9420773X. El de Florin no lo tengo aquí, está en su cartera.\n\nGracias, Mihaela\n\nEnviado desde mi móvil',
    oro: [
      // Convención de los otros cuatro corpus: el buzón genérico de un despacho también se tapa (29-sep).,
      ['CORREO', 'guardia@bonetadvocats.com'],
      ['PERSONA', 'Mihaela Dumitrescu'],
      ['CORREO', 'mihaela.dumi84@yahoo.es'],
      ['PERSONA', 'Florin'],
      ['PERSONA', 'Carmen'],
      ['ORGANISMO', 'Guardia Civil'],
      ['DATO_PENAL', 'ya tiene antecedentes por conducir sin carnet de 2022'],
      ['CAT_ESPECIAL', 'metadona'],
      ['ORGANISMO', 'CAD de Manacor'],
      ['CAT_ESPECIAL', 'diabético'],
      ['TELEFONO', '671.09.43.28'],
      ['PERSONA', 'Costel'],
      ['TELEFONO', '0040 744 512 309'],
      ['DIRECCION', 'Camí de Son Fangos, 14, 1.º, 07500 Manacor'],
      ['NIE', 'Y9420773X'],
      ['PERSONA', 'Mihaela'],
    ],
  },
  {
    id: 'e-dum-auto-prision',
    fuente: 'Auto de prisión provisional comunicada y sin fianza',
    clase: 'nativo',
    expediente: 'exp-dumitrescu',
    texto: 'TRIBUNAL D\'INSTÀNCIA DE PALMA — SECCIÓ D\'INSTRUCCIÓ, PLAÇA 2\nTRIBUNAL DE INSTANCIA DE PALMA, SECCIÓN DE INSTRUCCIÓN, PLAZA 2\nDiligencias previas 1037/2026\n\nAUTO DE PRISIÓN PROVISIONAL\n\nEn Palma, a 8 de junio de 2026.\n\nHECHOS\nPRIMERO.- Por atestado n.º 2026-004471 del Puesto de la Guardia Civil de Alcúdia, instruido por los agentes con TIP S-81234-Q y R-60718-K, ha sido puesto a disposición judicial FLORIN DUMITRESCU, con NIE X6629015R, como presunto autor de un delito de contrabando y de un delito de resistencia a agentes de la autoridad. En el camión con matrícula B-3456-TX se hallaron 4.800 cartones de tabaco. El otro conductor, Vasile Ionescu Marin, se dio a la fuga.\n\nRAZONAMIENTOS JURÍDICOS\nPRIMERO.- Conforme a los artículos 502 y 503 LECrim, concurren indicios racionales de criminalidad y riesgo de fuga, dado que el investigado carece de arraigo laboral y tiene familia en Rumanía. Dumitrescu ha manifestado seguir un programa de mantenimiento con metadona, lo que se pondrá en conocimiento del centro penitenciario para que garantice la continuidad del tratamiento.\nSEGUNDO.- El Ministerio Fiscal, representado por D.ª Elena Torrens Massanet, interesó la prisión.\n\nPARTE DISPOSITIVA\nSe decreta la PRISIÓN PROVISIONAL COMUNICADA Y SIN FIANZA de Florin Dumitrescu.\n\nAixí ho mana i signa el magistrat Ferran Estapé Roig. En dono fe.\nEl lletrat de l\'Administració de Justícia, Miquel Àngel Oliver Ferrà.',
    oro: [
      ['ORGANO', 'TRIBUNAL D\'INSTÀNCIA DE PALMA — SECCIÓ D\'INSTRUCCIÓ, PLAÇA 2'],
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE PALMA, SECCIÓN DE INSTRUCCIÓN, PLAZA 2'],
      ['AUTOS', 'Diligencias previas 1037/2026'],
      ['ORGANISMO', 'Puesto de la Guardia Civil de Alcúdia'],
      ['TIP', 'S-81234-Q'],
      ['TIP', 'R-60718-K'],
      ['PERSONA', 'FLORIN DUMITRESCU'],
      ['NIE', 'X6629015R'],
      ['MATRICULA', 'B-3456-TX'],
      ['PERSONA', 'Vasile Ionescu Marin'],
      ['NORMA', 'artículos 502 y 503 LECrim'],
      ['PERSONA', 'Dumitrescu'],
      ['CAT_ESPECIAL', 'un programa de mantenimiento con metadona'],
      ['PERSONA', 'Elena Torrens Massanet'],
      ['PERSONA', 'Florin Dumitrescu'],
      ['PONENTE', 'Ferran Estapé Roig'],
      ['LAJ', 'Miquel Àngel Oliver Ferrà'],
    ],
  },
  {
    id: 'e-dum-recurso-reforma',
    fuente: 'Recurso de reforma y subsidiario de apelación contra el auto de prisión',
    clase: 'nativo',
    expediente: 'exp-dumitrescu',
    texto: 'AL TRIBUNAL DE INSTANCIA DE PALMA, SECCIÓN DE INSTRUCCIÓN, PLAZA 2\nDP 1037/2026\n\nDon Bartomeu Bonet Frau, abogado del ICAIB n.º 6.207, en defensa de don Florin Dumitrescu, interpone RECURSO DE REFORMA y subsidiario de APELACIÓN:\n\n1. Arraigo. El Sr. Dumitrescu reside desde 2017 con su esposa, D.ª Mihaela Dumitrescu, en el domicilio familiar de Manacor, y ambos tienen una hija escolarizada, Daria Dumitrescu, de 9 años. Se aporta contrato de trabajo de la esposa en el Hotel Cala Millor Garden, S.A., con domicilio social en calle Son Moro, 5, 07560 Sant Llorenç des Cardassar.\n\n2. La única condena de mi defendido, por un delito contra la seguridad vial de 2022, está cancelada o es cancelable, por lo que no puede fundar el riesgo de fuga (art. 136 CP).\n\n3. Salud. Dumitrescu padece diabetes mellitus tipo 2 insulinodependiente y hepatitis C crónica, según el informe clínico del Hospital de Manacor que se acompaña. Su permanencia en prisión compromete la continuidad asistencial.\n\n4. Se ofrece como alternativa la comparecencia semanal y la retirada del pasaporte.\n\nPalma, 10 de junio de 2026.',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE PALMA, SECCIÓN DE INSTRUCCIÓN, PLAZA 2'],
      ['AUTOS', 'DP 1037/2026'],
      ['PERSONA', 'Bartomeu Bonet Frau'],
      ['PERSONA', 'Florin Dumitrescu'],
      ['PERSONA', 'Dumitrescu'],
      ['PERSONA', 'Mihaela Dumitrescu'],
      ['PERSONA', 'Daria Dumitrescu'],
      ['OBJETO', 'La única condena de mi defendido, por un delito contra la seguridad vial de 2022, está cancelada o es cancelable'],
      ['NORMA', 'art. 136 CP'],
      ['CAT_ESPECIAL', 'diabetes mellitus tipo 2 insulinodependiente y hepatitis C crónica'],
      ['CAT_ESPECIAL', 'informe clínico'],
      ['ORGANISMO', 'Hospital de Manacor'],
    ],
    ambiguo: ['Dumitrescu'],
  },

  // ───────────────────────── EXPEDIENTE: Audiencia de Málaga (Cuesta Llano) ─────────────────────────
  {
    id: 'e-mal-sentencia-penal',
    fuente: 'Sentencia de la Audiencia Provincial con tres acusados por robo con violencia',
    clase: 'nativo',
    expediente: 'exp-malaga-cuesta',
    texto: 'AUDIENCIA PROVINCIAL DE MÁLAGA — SECCIÓN SEGUNDA\nRollo de Sala 64/2025 — Procedimiento abreviado 902/2024 del Tribunal de Instancia de Marbella, Sección de Instrucción, Plaza 1\n\nSENTENCIA N.º 311/2026\n\nIlmos. Sres.: Presidente D. Rafael Carmona Gálvez; Magistrados D.ª Inmaculada Rueda Pozo y D. Álvaro Lagos Benítez (ponente).\n\nEn Málaga, a 17 de abril de 2026.\n\nAcusados: AITOR CUESTA LLANO, con DNI 52190364Y; IKER CUESTA LLANO, con DNI 44718903A; e IONEL VASILE, con NIE Y7514386R.\n\nHECHOS PROBADOS\nPRIMERO.- Sobre las 23:00 horas del 2 de julio de 2024, los tres acusados abordaron a Hans-Peter Brandt en la calle Ancha de Marbella, le golpearon y le sustrajeron un reloj valorado en 18.000 euros. El Sr. Brandt sufrió fractura de dos arcos costales.\nSEGUNDO.- Aitor Cuesta Llano había sido condenado ejecutoriamente por sentencia firme de 12 de enero de 2022 del Juzgado de lo Penal n.º 5 de Málaga a la pena de un año de prisión por un delito de robo con fuerza.\nTERCERO.- Ionel Vasile actuó con sus facultades volitivas levemente disminuidas por su drogadicción de larga evolución, estando en tratamiento con metadona desde 2019.\nCUARTO.- La testigo Estefanía Heredia Amador, cuñada de Iker, declaró que Cuesta llegó a casa esa noche con el reloj. Consta que la testigo cumplió condena en el Centro Penitenciario de Alhaurín de la Torre hasta 2023.\n\nFALLO\nCondenamos a AITOR CUESTA LLANO con la agravante de reincidencia a cinco años de prisión; a IKER CUESTA LLANO a tres años y seis meses; y a IONEL VASILE, con la atenuante analógica de drogadicción, a tres años.\n\nLa presente resolución no es firme; cabe recurso de apelación ante la Sala de lo Civil y Penal del Tribunal Superior de Justicia de Andalucía, Ceuta y Melilla.',
    oro: [
      ['ORGANO', 'AUDIENCIA PROVINCIAL DE MÁLAGA — SECCIÓN SEGUNDA'],
      ['AUTOS', 'Rollo de Sala 64/2025'],
      ['AUTOS', 'Procedimiento abreviado 902/2024'],
      ['ORGANO', 'Tribunal de Instancia de Marbella, Sección de Instrucción, Plaza 1'],
      ['PONENTE', 'Rafael Carmona Gálvez'],
      ['PONENTE', 'Inmaculada Rueda Pozo'],
      ['PONENTE', 'Álvaro Lagos Benítez'],
      ['PERSONA', 'AITOR CUESTA LLANO'],
      ['DNI', '52190364Y'],
      ['PERSONA', 'IKER CUESTA LLANO'],
      ['DNI', '44718903A'],
      ['PERSONA', 'IONEL VASILE'],
      ['NIE', 'Y7514386R'],
      ['PERSONA', 'Hans-Peter Brandt'],
      ['PERSONA', 'Brandt'],
      ['CAT_ESPECIAL', 'fractura de dos arcos costales'],
      ['PERSONA', 'Aitor Cuesta Llano'],
      ['OBJETO', 'había sido condenado ejecutoriamente por sentencia firme de 12 de enero de 2022 del Juzgado de lo Penal n.º 5 de Málaga a la pena de un año de prisión por un delito de robo con fuerza'],
      ['PERSONA', 'Ionel Vasile'],
      ['OBJETO', 'drogadicción de larga evolución'],
      ['CAT_ESPECIAL', 'metadona'],
      ['PERSONA', 'Estefanía Heredia Amador'],
      ['PERSONA', 'Iker'],
      ['PERSONA', 'Cuesta'],
      ['DATO_PENAL', 'la testigo cumplió condena en el Centro Penitenciario de Alhaurín de la Torre hasta 2023'],
      ['OBJETO', 'reincidencia'],
      ['OBJETO', 'drogadicción'],
      ['ORGANO', 'Sala de lo Civil y Penal del Tribunal Superior de Justicia de Andalucía, Ceuta y Melilla'],
    ],
    ambiguo: ['Cuesta'],
  },
  {
    id: 'e-mal-casacion',
    fuente: 'Escrito de preparación e interposición de recurso de casación ante la Sala Segunda',
    clase: 'nativo',
    expediente: 'exp-malaga-cuesta',
    texto: 'A LA SALA SEGUNDA DEL TRIBUNAL SUPREMO\n\nRecurso de casación n.º 10482/2026 contra la sentencia de 9 de julio de 2026 de la Sala de lo Civil y Penal del TSJ de Andalucía, Ceuta y Melilla (rollo de apelación 211/2026), dimanante del rollo 64/2025 de la Audiencia Provincial de Málaga, Sección 2.ª.\n\nDoña Pilar Azpeitia Echániz, Procuradora de los Tribunales, en nombre de DON IKER CUESTA LLANO, bajo la dirección del letrado don Juan Ignacio Montes de Oca Ferrer, formaliza RECURSO DE CASACIÓN por los siguientes\n\nMOTIVOS\n\nPRIMERO.- Por infracción de precepto constitucional (art. 852 LECrim), vulneración del derecho a la presunción de inocencia (art. 24.2 CE). La condena de Iker descansa exclusivamente en el testimonio de su cuñada, la Sra. Heredia, enemistada con él. Además, la testigo padece un trastorno límite de la personalidad, según consta en el informe psiquiátrico del folio 344, lo que afecta a su credibilidad.\n\nSEGUNDO.- Infracción de ley (art. 849.1 LECrim) por indebida aplicación del artículo 242.1 CP. Cuesta no empleó violencia: fue su hermano Aitor quien golpeó a la víctima.\n\nTERCERO.- La propia sentencia de instancia reconoce que Iker trabajaba en el taller de su suegro, don Manuel Heredia Cortés, y que su hija menor, Alba Cuesta Heredia, sufre una cardiopatía congénita.\n\nSe cita la STS 147/2024, de 21 de febrero (ROJ: STS 890/2024).\n\nMadrid, 30 de julio de 2026.',
    oro: [
      ['ORGANO', 'SALA SEGUNDA DEL TRIBUNAL SUPREMO'],
      ['AUTOS', 'Recurso de casación n.º 10482/2026'],
      ['ORGANO', 'Sala de lo Civil y Penal del TSJ de Andalucía, Ceuta y Melilla'],
      ['AUTOS', 'rollo de apelación 211/2026'],
      ['AUTOS', 'rollo 64/2025'],
      ['ORGANO', 'Audiencia Provincial de Málaga, Sección 2.ª'],
      ['PERSONA', 'Pilar Azpeitia Echániz'],
      ['PERSONA', 'IKER CUESTA LLANO'],
      ['PERSONA', 'Juan Ignacio Montes de Oca Ferrer'],
      ['NORMA', 'art. 852 LECrim'],
      ['NORMA', 'art. 24.2 CE'],
      ['PERSONA', 'Iker'],
      ['PERSONA', 'Heredia'],
      ['CAT_ESPECIAL', 'trastorno límite de la personalidad'],
      ['CAT_ESPECIAL', 'informe psiquiátrico'],
      ['NORMA', 'art. 849.1 LECrim'],
      ['NORMA', 'artículo 242.1 CP'],
      ['PERSONA', 'Cuesta'],
      ['PERSONA', 'Aitor'],
      ['PERSONA', 'Manuel Heredia Cortés'],
      ['PERSONA', 'Alba Cuesta Heredia'],
      ['CAT_ESPECIAL', 'cardiopatía congénita'],
      ['NORMA', 'STS 147/2024, de 21 de febrero'],
      ['ROJ', 'STS 890/2024'],
    ],
    ambiguo: ['Cuesta', 'Heredia'],
  },

  // ───────────────────────── FRAGMENTOS SUELTOS ─────────────────────────
  {
    id: 'e-seguro-vida',
    fuente: 'Reclamación de la beneficiaria al servicio de atención al cliente de una aseguradora de vida',
    clase: 'nativo',
    texto: 'A LA ATENCIÓN DEL SERVICIO DE ATENCIÓN AL CLIENTE DE AURIGA VIDA Y PENSIONES, S.A.\nPaseo de la Castellana, 95, planta 14, 28046 Madrid\n\nDoña Guacimara Santana Perdomo, con DNI 09342751J, domiciliada en C/ León y Castillo, 231, 4.º izq., 35005 Las Palmas de Gran Canaria, como beneficiaria del seguro de vida vinculado a préstamo hipotecario suscrito por su pareja de hecho, don Airam Déniz Suárez, fallecido el 11 de febrero de 2026, EXPONE:\n\n1. Que la compañía rechaza el pago del capital (145.000 euros) alegando que el asegurado ocultó en el cuestionario de salud de 2019 que padecía diabetes mellitus tipo 1.\n\n2. Que el cuestionario lo rellenó el empleado de la sucursal, don Jonay Hernández Afonso, sin leer las preguntas al asegurado, como declarará él mismo.\n\n3. Que la causa de la muerte, según el certificado médico de defunción, fue un infarto agudo de miocardio, sin relación con la diabetes, y que Airam nunca estuvo hospitalizado por ella.\n\n4. Que la jurisprudencia (STS 1.ª 333/2020, de 22 de junio) exige que el asegurador pruebe el dolo o la culpa grave.\n\nSOLICITA el abono del capital en la cuenta ES36-0049-1500-0027-1034-5678.\n\nContacto: guacisantana@gmail.com · 928 36 47 12 · 616 90 33 84.',
    oro: [
      ['PERSONA', 'Guacimara Santana Perdomo'],
      ['DNI', '09342751J'],
      ['DIRECCION', 'C/ León y Castillo, 231, 4.º izq., 35005 Las Palmas de Gran Canaria'],
      ['PERSONA', 'Airam Déniz Suárez'],
      ['CAT_ESPECIAL', 'cuestionario de salud'],
      ['CAT_ESPECIAL', 'diabetes mellitus tipo 1'],
      ['PERSONA', 'Jonay Hernández Afonso'],
      ['CAT_ESPECIAL', 'certificado médico de defunción'],
      ['CAT_ESPECIAL', 'un infarto agudo de miocardio'],
      ['CAT_ESPECIAL', 'diabetes'],
      ['PERSONA', 'Airam'],
      ['CAT_ESPECIAL', 'hospitalizado'],
      ['NORMA', 'STS 1.ª 333/2020, de 22 de junio'],
      ['IBAN', 'ES36-0049-1500-0027-1034-5678'],
      ['CORREO', 'guacisantana@gmail.com'],
      ['TELEFONO', '928 36 47 12'],
      ['TELEFONO', '616 90 33 84'],
    ],
  },
  {
    id: 'e-alta-hospitalaria',
    fuente: 'Informe de alta hospitalaria de neurología escaneado',
    clase: 'ocr',
    expediente: 'exp-alvarez-dependencia',
    texto: 'SERVICIO DE SALUD DEL PRINCIPADO DE ASTURIAS\nHOSPITAL UNIVERSITARIO CENTRAL DE ASTURIAS - SERVICIO DE NEUROLOGIA\nINFORME DE ALTA\n\nPACIENTE: ALVAREZ MENENDEZ, PELAYO    DNI: 77051286K    EDAD: 79\nDOMICILIO: C/ URIA 44 5 DCHA 33003 OVIEDO    TFNO: 985.21.34.07\nFECHA INGRESO: 02/05/2026    FECHA ALTA: 19/05/2026\n\nMOTIVO DE INGRESO: PERDIDA DE FUERZA EN HEMICUERPO DERECHO Y ALTERACION DEL LENGUAJE.\nANTECEDENTES: HTA. FIBRILACION AURICULAR NO ANTICOAGULADA. EXFUMADOR.\nJUICIO CLINICO: ICTUS ISQUEMICO DE ARTERIA CEREBRAL MEDIA IZQUIERDA DE ORIGEN CARDIOEMBOLICO. AFASIA MIXTA.\nTRATAMIENTO AL ALTA: APIXABAN 5 MG CADA 12 HORAS. ATORVASTATINA 40 MG.\nSITUACION FUNCIONAL: RANKIN 4. PRECISA AYUDA PARA ABVD.\n\nSE INFORMA A SU HIJA, D. COVADONGA ALVAREZ GARCIA (TFNO 686 14 03 52), QUE SOLICITA INICIAR TRAMITES DE DEPENDENCIA.\n\nFDO. DRA. XANA SUAREZ FERNANDEZ - FEA NEUROLOGIA - COLEG. 33/08812',
    oro: [
      ['ORGANISMO', 'SERVICIO DE SALUD DEL PRINCIPADO DE ASTURIAS'],
      ['ORGANISMO', 'HOSPITAL UNIVERSITARIO CENTRAL DE ASTURIAS'],
      ['CAT_ESPECIAL', 'INFORME DE ALTA'],
      ['PERSONA', 'ALVAREZ MENENDEZ, PELAYO'],
      ['DNI', '77051286K'],
      ['DIRECCION', 'C/ URIA 44 5 DCHA 33003 OVIEDO'],
      ['TELEFONO', '985.21.34.07'],
      ['CAT_ESPECIAL', 'PERDIDA DE FUERZA EN HEMICUERPO DERECHO Y ALTERACION DEL LENGUAJE'],
      ['CAT_ESPECIAL', 'HTA. FIBRILACION AURICULAR NO ANTICOAGULADA. EXFUMADOR'],
      ['CAT_ESPECIAL', 'ICTUS ISQUEMICO DE ARTERIA CEREBRAL MEDIA IZQUIERDA DE ORIGEN CARDIOEMBOLICO. AFASIA MIXTA'],
      ['CAT_ESPECIAL', 'APIXABAN 5 MG CADA 12 HORAS. ATORVASTATINA 40 MG'],
      ['CAT_ESPECIAL', 'RANKIN 4. PRECISA AYUDA PARA ABVD'],
      ['PERSONA', 'COVADONGA ALVAREZ GARCIA'],
      ['TELEFONO', '686 14 03 52'],
      ['PERSONA', 'XANA SUAREZ FERNANDEZ'],
    ],
  },
  {
    id: 'e-dependencia',
    fuente: 'Resolución autonómica de reconocimiento de grado de dependencia y PIA',
    clase: 'nativo',
    expediente: 'exp-alvarez-dependencia',
    texto: 'CONSEJERÍA DE DERECHOS SOCIALES Y BIENESTAR\nPRINCIPADO DE ASTURIAS\n\nRESOLUCIÓN de reconocimiento de la situación de dependencia\nExpediente DEP/2026/33/07714\n\nVista la solicitud presentada el 26 de mayo de 2026 por don Pelayo Álvarez Menéndez, con DNI 77051286K, a través de su hija y guardadora de hecho, doña Covadonga Álvarez García, con DNI 25839106D, y el informe de condiciones de salud emitido por su médica de atención primaria,\n\nRESUELVO:\n\nPRIMERO.- Reconocer a don Pelayo Álvarez Menéndez el GRADO II de dependencia severa, con una puntuación BVD de 62 puntos, derivado de secuelas de ictus con afasia y hemiparesia derecha.\n\nSEGUNDO.- Aprobar el Programa Individual de Atención consistente en la prestación económica para cuidados en el entorno familiar, siendo cuidadora no profesional su nieta, doña Llara Rodríguez Álvarez, con domicilio en Barrio La Carrera, n.º 12, bajo, 33519 Siero.\n\nTERCERO.- La prestación (387,64 euros/mes) se abonará en la cuenta ES35 0182 5322 2102 0156 7890.\n\nContra la presente resolución cabe recurso de alzada ante la titular de la Consejería en el plazo de un mes (arts. 121 y 122 de la Ley 39/2015).\n\nOviedo, 4 de septiembre de 2026. La Directora General de Cuidados, Dependencia y Discapacidad, Ana Belén Fueyo Llaneza.',
    oro: [
      ['ORGANISMO', 'CONSEJERÍA DE DERECHOS SOCIALES Y BIENESTAR'],
      ['AUTOS', 'Expediente DEP/2026/33/07714'],
      ['PERSONA', 'Pelayo Álvarez Menéndez'],
      ['DNI', '77051286K'],
      ['PERSONA', 'Covadonga Álvarez García'],
      ['DNI', '25839106D'],
      ['CAT_ESPECIAL', 'informe de condiciones de salud'],
      ['CAT_ESPECIAL', 'GRADO II de dependencia severa, con una puntuación BVD de 62 puntos'],
      ['CAT_ESPECIAL', 'secuelas de ictus con afasia y hemiparesia derecha'],
      ['PERSONA', 'Llara Rodríguez Álvarez'],
      ['DIRECCION', 'Barrio La Carrera, n.º 12, bajo, 33519 Siero'],
      ['IBAN', 'ES35 0182 5322 2102 0156 7890'],
      ['NORMA', 'arts. 121 y 122 de la Ley 39/2015'],
      ['PERSONA', 'Ana Belén Fueyo Llaneza'],
    ],
  },
  {
    id: 'e-forense-sanidad',
    fuente: 'Informe médico-forense de sanidad escaneado',
    clase: 'ocr',
    texto: 'INSTITUTO DE MEDICINA LEGAL Y CIENCIAS FORENSES DE MADRID\nSERVICIO DE CLINICA MEDICO FORENSE - SEDE MOSTOLES\n\nINFORME DE SANIDAD\nTRIBUNAL DE INSTANCIA DE MOSTOLES, SECCION DE INSTRUCCION, PLAZA 4 - DILIGENCIAS PREVIAS 1422/2026\n\nLESIONADA: YESSENIA CAROLINA PAREDES RUIZ, NIE Z0452108W, NATURAL DE GUAYAQUIL (ECUADOR).\n\nLESIONES: FRACTURA DE HUESOS PROPIOS NASALES Y HEMATOMA PERIORBITARIO BILATERAL.\nTRATAMIENTO: ADEMAS DE LA PRIMERA ASISTENCIA PRECISO TRATAMIENTO QUIRURGICO (REDUCCION CERRADA BAJO ANESTESIA LOCAL).\nTIEMPO DE CURACION: 45 DIAS, DE LOS QUE 7 FUERON DE PERJUICIO PERSONAL MODERADO.\nSECUELAS: PERJUICIO ESTETICO LIGERO (3 PUNTOS) POR DESVIACION DEL TABIQUE.\nOTROS DATOS: REFIERE EPILEPSIA EN TRATAMIENTO CON LEVETIRACETAM, SIN RELACION CON LOS HECHOS. LA LESIONADA INDICA QUE LA AGRESORA, SU EXCOMPANERA DE PISO MILAGROS CHAMORRO VIERA, LE GOLPEO CON EL TELEFONO MOVIL.\n\nMOSTOLES, 21 DE JULIO DE 2026\nEL MEDICO FORENSE: ANTONIO JESUS BLANCO SORIA',
    oro: [
      ['ORGANISMO', 'INSTITUTO DE MEDICINA LEGAL Y CIENCIAS FORENSES DE MADRID'],
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE MOSTOLES, SECCION DE INSTRUCCION, PLAZA 4'],
      ['AUTOS', 'DILIGENCIAS PREVIAS 1422/2026'],
      ['PERSONA', 'YESSENIA CAROLINA PAREDES RUIZ'],
      ['NIE', 'Z0452108W'],
      ['CAT_ESPECIAL', 'FRACTURA DE HUESOS PROPIOS NASALES Y HEMATOMA PERIORBITARIO BILATERAL'],
      ['CAT_ESPECIAL', 'TRATAMIENTO QUIRURGICO (REDUCCION CERRADA BAJO ANESTESIA LOCAL)'],
      ['CAT_ESPECIAL', 'PERJUICIO ESTETICO LIGERO (3 PUNTOS) POR DESVIACION DEL TABIQUE'],
      ['CAT_ESPECIAL', 'EPILEPSIA'],
      ['CAT_ESPECIAL', 'LEVETIRACETAM'],
      ['PERSONA', 'MILAGROS CHAMORRO VIERA'],
      ['PERSONA', 'ANTONIO JESUS BLANCO SORIA'],
    ],
  },
  {
    id: 'e-irpf-reposicion',
    fuente: 'Recurso de reposición contra liquidación provisional del IRPF',
    clase: 'nativo',
    texto: 'A LA DEPENDENCIA REGIONAL DE GESTIÓN TRIBUTARIA DE LA DELEGACIÓN ESPECIAL DE LA AEAT EN VALENCIA\n\nReferencia de la liquidación: 2025GRC46470183L — IRPF ejercicio 2024\n\nDon Josep Vicent Albiol Mora, NIF 72864015S, con domicilio en Avinguda de Lledó, 73, 5a, 12004 Castelló de la Plana, teléfono (+34) 964-21-87-65, interpone RECURSO DE REPOSICIÓN (art. 223 LGT):\n\nPRIMERA.- La Administración elimina la deducción por descendiente con discapacidad respecto de su hijo, Joel Albiol Esteve, alegando que no se ha acreditado el grado. Se aporta resolución de la Conselleria de Servicios Sociales que reconoce a Joel una discapacidad del 65 % por síndrome de Down.\n\nSEGUNDA.- Se suprime indebidamente como gasto deducible de los rendimientos del trabajo la cuota de 186 euros satisfecha al sindicato Intersindical Valenciana, de la que el recurrente es afiliado desde 2011, acreditada con el certificado del sindicato.\n\nTERCERA.- La pensión compensatoria abonada a su ex cónyuge, doña Rosa María Esteve Ballester, con DNI 46209183K, se fijó en la sentencia de divorcio de 2019 del Juzgado de Primera Instancia n.º 3 de Castelló (autos 511/2018).\n\nSOLICITA la anulación de la liquidación y la devolución de 1.412,37 euros en la cuenta ES31 2038 1024 1960 0078 9123.\n\nCastelló de la Plana, 18 de septiembre de 2026.',
    oro: [
      // Duda 2 (Juan): la discapacidad del hijo es categoría especial.,
      ['CAT_ESPECIAL', 'discapacidad'],
      ['ORGANISMO', 'DEPENDENCIA REGIONAL DE GESTIÓN TRIBUTARIA DE LA DELEGACIÓN ESPECIAL DE LA AEAT EN VALENCIA'],
      ['AUTOS', '2025GRC46470183L'],
      ['PERSONA', 'Josep Vicent Albiol Mora'],
      ['DNI', '72864015S'],
      ['DIRECCION', 'Avinguda de Lledó, 73, 5a, 12004 Castelló de la Plana'],
      ['TELEFONO', '(+34) 964-21-87-65'],
      ['NORMA', 'art. 223 LGT'],
      ['PERSONA', 'Joel Albiol Esteve'],
      ['ORGANISMO', 'Conselleria de Servicios Sociales'],
      ['PERSONA', 'Joel'],
      ['CAT_ESPECIAL', 'discapacidad del 65 %'],
      ['CAT_ESPECIAL', 'síndrome de Down'],
      ['CAT_ESPECIAL', 'cuota de 186 euros satisfecha al sindicato Intersindical Valenciana'],
      ['CAT_ESPECIAL', 'afiliado'],
      ['PERSONA', 'Rosa María Esteve Ballester'],
      ['DNI', '46209183K'],
      ['ORGANO', 'Juzgado de Primera Instancia n.º 3 de Castelló'],
      ['AUTOS', 'autos 511/2018'],
      ['IBAN', 'ES31 2038 1024 1960 0078 9123'],
    ],
  },
  {
    id: 'e-it-alta-impugnada',
    fuente: 'Demanda de impugnación de alta médica emitida por la mutua',
    clase: 'nativo',
    texto: 'AL TRIBUNAL DE INSTANCIA DE SEVILLA, SECCIÓN DE LO SOCIAL, PLAZA QUE POR REPARTO CORRESPONDA\n\nDOÑA ROSARIO MATA CORDERO, con DNI 16482079A, n.º de afiliación a la Seguridad Social 41/1038726543, domiciliada en la avda. de la Paz, 40, portal 3, 2.º D, 41013 Sevilla, representada por la graduada social doña Macarena Oliva Vergara, formula DEMANDA DE IMPUGNACIÓN DE ALTA MÉDICA (art. 140.3 LRJS) contra la MUTUA COLABORADORA CON LA SEGURIDAD SOCIAL N.º 274 y el INSS.\n\nHECHOS\n\nPRIMERO.- La actora, limpiadora, inició un proceso de incapacidad temporal el 14 de enero de 2026, según parte de baja con diagnóstico de hernia discal L5-S1 con radiculopatía S1 izquierda.\n\nSEGUNDO.- La mutua emitió parte de alta el 2 de septiembre de 2026 por mejoría que permite trabajar. Sin embargo, Mata sigue en tratamiento con pregabalina 150 mg y tramadol, está pendiente de una resonancia magnética de control y la Unidad del Dolor del Hospital Virgen del Rocío la ha incluido en lista de espera para radiofrecuencia.\n\nTERCERO.- El 8 de septiembre presentó disconformidad ante el INSS, que confirmó el alta.\n\nSUPLICO se declare que el alta fue prematura y que la actora permanecía en situación de incapacidad temporal.\n\nTeléfono de la actora: 955.43.21.09.',
    oro: [
      ['CAT_ESPECIAL', 'ALTA MÉDICA'],
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE SEVILLA, SECCIÓN DE LO SOCIAL'],
      ['PERSONA', 'ROSARIO MATA CORDERO'],
      ['DNI', '16482079A'],
      ['NUSS', '41/1038726543'],
      ['DIRECCION', 'avda. de la Paz, 40, portal 3, 2.º D, 41013 Sevilla'],
      ['PERSONA', 'Macarena Oliva Vergara'],
      ['NORMA', 'art. 140.3 LRJS'],
      ['ORGANISMO', 'MUTUA COLABORADORA CON LA SEGURIDAD SOCIAL N.º 274'],
      ['ORGANISMO', 'INSS'],
      ['CAT_ESPECIAL', 'incapacidad temporal'],
      ['CAT_ESPECIAL', 'parte de baja'],
      ['CAT_ESPECIAL', 'hernia discal L5-S1 con radiculopatía S1 izquierda'],
      ['CAT_ESPECIAL', 'parte de alta'],
      ['PERSONA', 'Mata'],
      ['CAT_ESPECIAL', 'pregabalina 150 mg y tramadol'],
      ['CAT_ESPECIAL', 'una resonancia magnética de control'],
      ['ORGANISMO', 'Unidad del Dolor del Hospital Virgen del Rocío'],
      ['CAT_ESPECIAL', 'radiofrecuencia'],
      ['TELEFONO', '955.43.21.09'],
    ],
  },
  {
    id: 'e-arraigo',
    fuente: 'Solicitud de autorización de residencia temporal por arraigo sociolaboral',
    clase: 'nativo',
    texto: 'A LA OFICINA DE EXTRANJERÍA DE LLEIDA — SUBDELEGACIÓN DEL GOBIERNO\n\nSOLICITUD DE AUTORIZACIÓN DE RESIDENCIA TEMPORAL POR CIRCUNSTANCIAS EXCEPCIONALES — ARRAIGO SOCIOLABORAL (art. 127 b del Reglamento aprobado por RD 1155/2024)\n\nSolicitante: DIALLO BA, Mamadou, nacional de Senegal, NIE Z1573620B, empadronado en carrer del Canyeret, 9, 3r 1a, 25007 Lleida desde marzo de 2023. Teléfono: 632 55 18 07.\n\nEmpleadora: doña Ana Isabel de la Fuente Cuervo, DNI 33928410Y, titular de la explotación frutícola «Mas del Cuervo» en la partida Grealó, que ofrece un contrato de 30 horas semanales como peón.\n\nDocumentación: pasaporte en vigor; certificado de empadronamiento histórico; certificado de antecedentes penales de Senegal; informe de esfuerzo de integración emitido por la Paeria; contrato firmado por las partes.\n\nSe hace constar que el solicitante convive con su primo, don Ousmane Ba Ndiaye, titular de autorización de residencia de larga duración, y que colabora como voluntario con la parroquia de Sant Martí y con la comunidad musulmana del barrio.\n\nRepresentante: Sra. Aminata Touré, mediadora de Càritas Diocesana de Lleida (aminata.toure@caritaslleida.org).',
    oro: [
      ['ORGANISMO', 'OFICINA DE EXTRANJERÍA DE LLEIDA'],
      ['ORGANISMO', 'SUBDELEGACIÓN DEL GOBIERNO'],
      ['NORMA', 'art. 127 b del Reglamento aprobado por RD 1155/2024'],
      ['PERSONA', 'DIALLO BA, Mamadou'],
      ['NIE', 'Z1573620B'],
      ['DIRECCION', 'carrer del Canyeret, 9, 3r 1a, 25007 Lleida'],
      ['TELEFONO', '632 55 18 07'],
      ['PERSONA', 'Ana Isabel de la Fuente Cuervo'],
      ['DNI', '33928410Y'],
      ['ORGANISMO', 'Paeria'],
      ['PERSONA', 'Ousmane Ba Ndiaye'],
      ['CAT_ESPECIAL', 'la comunidad musulmana del barrio'],
      ['PERSONA', 'Aminata Touré'],
      ['CORREO', 'aminata.toure@caritaslleida.org'],
    ],
  },
  {
    id: 'e-asilo',
    fuente: 'Alegaciones en solicitud de protección internacional de un objetor ucraniano',
    clase: 'nativo',
    texto: 'A LA OFICINA DE ASILO Y REFUGIO — MINISTERIO DEL INTERIOR\nExpediente de protección internacional n.º 28079260041238\n\nDon Oleksandr Kovalenko, NIE Y6071248K, con domicilio a efectos de notificaciones en calle del Arroyo del Olivar, 49, 2.º C, 28018 Madrid, formula ALEGACIONES:\n\n1. El solicitante es Testigo de Jehová desde 2014 y objetor de conciencia al servicio armado. En Ucrania la ley de movilización no prevé servicio civil alternativo durante la ley marcial, y dos miembros de su congregación en Zhytomyr fueron condenados a tres años de prisión por negarse a empuñar las armas.\n\n2. Su esposa, Olena Petrenko, y su hijo menor, Maksym Kovalenko, residen con él. Kovalenko teme que su hijo, de 17 años, sea movilizado al cumplir la edad.\n\n3. Durante la detención en el puesto fronterizo de Chop sufrió una fractura de muñeca por la que fue atendido en el Hospital de Uzhhorod; aporta el informe de urgencias traducido.\n\n4. Contacto en Ucrania del pastor de la congregación, Sr. Taras Melnyk: +380 67 412 3390.\n\nMadrid, 1 de septiembre de 2026.\nLetrada: Irene Castañeda Villalobos (CEAR).',
    oro: [
      ['ORGANISMO', 'OFICINA DE ASILO Y REFUGIO'],
      ['ORGANISMO', 'MINISTERIO DEL INTERIOR'],
      ['AUTOS', 'Expediente de protección internacional n.º 28079260041238'],
      ['PERSONA', 'Oleksandr Kovalenko'],
      ['NIE', 'Y6071248K'],
      ['DIRECCION', 'calle del Arroyo del Olivar, 49, 2.º C, 28018 Madrid'],
      ['CAT_ESPECIAL', 'Testigo de Jehová'],
      ['CAT_ESPECIAL', 'objetor de conciencia al servicio armado'],
      ['PERSONA', 'Olena Petrenko'],
      ['PERSONA', 'Maksym Kovalenko'],
      ['PERSONA', 'Kovalenko'],
      ['CAT_ESPECIAL', 'una fractura de muñeca'],
      ['CAT_ESPECIAL', 'informe de urgencias'],
      ['PERSONA', 'Taras Melnyk'],
      ['TELEFONO', '+380 67 412 3390'],
      ['PERSONA', 'Irene Castañeda Villalobos'],
    ],
    ambiguo: ['Kovalenko'],
  },
  {
    id: 'e-razones-humanitarias',
    fuente: 'Solicitud de residencia por razones humanitarias por enfermedad grave sobrevenida',
    clase: 'nativo',
    texto: 'A L\'OFICINA D\'ESTRANGERIA DE BARCELONA\n\nSOLICITUD DE AUTORIZACIÓN DE RESIDENCIA TEMPORAL POR RAZONES HUMANITARIAS (art. 127 c RLOEX)\n\nSolicitante: MUHAMMAD ASIF CHAUDHRY, nacional de Pakistán, pasaporte en vigor, domiciliado en carrer de Sant Pau, 102, 3r 1a, 08001 Barcelona; teléfono 631-204-778; correo asif.chaudhry1979@gmail.com.\n\nFundamento: el solicitante padece una insuficiencia renal crónica terminal secundaria a nefropatía diabética y está en hemodiálisis tres veces por semana en el Hospital del Mar desde noviembre de 2025. Según el informe del nefrólogo Dr. Jaume Riba Canals, la interrupción del tratamiento le causaría la muerte en semanas y en su región de origen (Gujrat) no existe acceso garantizado a diálisis.\n\nSe acompaña certificado de su hermano, Imran Chaudhry, con NIE X8126047D, que asume su manutención y que es miembro de la comunidad ahmadí de Barcelona.',
    oro: [
      // Duda 5 (Juan): el documento clínico por su nombre se tapa.,
      ['CAT_ESPECIAL', 'informe del nefrólogo'],
      ['ORGANISMO', 'OFICINA D\'ESTRANGERIA DE BARCELONA'],
      ['NORMA', 'art. 127 c RLOEX'],
      ['PERSONA', 'MUHAMMAD ASIF CHAUDHRY'],
      ['DIRECCION', 'carrer de Sant Pau, 102, 3r 1a, 08001 Barcelona'],
      ['TELEFONO', '631-204-778'],
      ['CORREO', 'asif.chaudhry1979@gmail.com'],
      ['CAT_ESPECIAL', 'una insuficiencia renal crónica terminal secundaria a nefropatía diabética'],
      ['CAT_ESPECIAL', 'hemodiálisis tres veces por semana'],
      ['ORGANISMO', 'Hospital del Mar'],
      ['PERSONA', 'Jaume Riba Canals'],
      ['CAT_ESPECIAL', 'diálisis'],
      ['PERSONA', 'Imran Chaudhry'],
      ['NIE', 'X8126047D'],
      ['CAT_ESPECIAL', 'miembro de la comunidad ahmadí'],
    ],
  },
  {
    id: 'e-adopcion',
    fuente: 'Auto de constitución de adopción con dispensa del asentimiento materno',
    clase: 'nativo',
    texto: 'TRIBUNAL DE INSTANCIA DE ZARAGOZA\nSECCIÓN DE FAMILIA — PLAZA N.º 2\n\nExpediente de jurisdicción voluntaria de adopción 145/2026\n\nAUTO N.º 612/2026\n\nMagistrada-Jueza: Pilar Lasheras Bielsa\nEn Zaragoza, a 7 de julio de 2026.\n\nHECHOS\n\nPRIMERO.- El Instituto Aragonés de Servicios Sociales formuló propuesta de adopción de la menor A.M.G., nacida en 2021, a favor del matrimonio formado por don Diego Lanuza Gracia, con DNI 29817364A, y doña Helena Marín Sanz, con DNI 53604921V, con domicilio en calle Coso, 98, 4.º izda., 50001 Zaragoza, que la tienen en guarda con fines de adopción desde 2023.\n\nSEGUNDO.- La madre biológica, doña Jennifer Moreno Galán, fue oída. La declaración de desamparo de 2022 se fundó en su drogadicción grave y persistente, con abandono de los controles del CMAPA. Se tiene en cuenta asimismo que la Sra. Moreno es portadora del VIH y que la menor dio negativo en las pruebas de transmisión vertical.\n\nRAZONAMIENTOS JURÍDICOS\n\nÚNICO.- Conforme al artículo 177.2.2.º del Código Civil, no es necesario el asentimiento de la progenitora incursa en causa legal de privación de la patria potestad. El Ministerio Fiscal, en la persona de don Ramón Albar Oliván, informó favorablemente.\n\nPARTE DISPOSITIVA\n\nSe constituye la adopción de la menor, que en lo sucesivo se llamará Aitana Lanuza Marín.\n\nAsí lo acuerda y firma S.S.ª Pilar Lasheras Bielsa. Doy fe.\nEl Letrado de la Administración de Justicia: Jesús Ángel Sancho Pueyo.',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE ZARAGOZA\nSECCIÓN DE FAMILIA — PLAZA N.º 2'],
      ['AUTOS', 'Expediente de jurisdicción voluntaria de adopción 145/2026'],
      ['PONENTE', 'Pilar Lasheras Bielsa'],
      ['ORGANISMO', 'Instituto Aragonés de Servicios Sociales'],
      ['PERSONA', 'A.M.G.'],
      ['PERSONA', 'Diego Lanuza Gracia'],
      ['DNI', '29817364A'],
      ['PERSONA', 'Helena Marín Sanz'],
      ['DNI', '53604921V'],
      ['DIRECCION', 'calle Coso, 98, 4.º izda., 50001 Zaragoza'],
      ['PERSONA', 'Jennifer Moreno Galán'],
      ['OBJETO', 'drogadicción grave y persistente'],
      ['CAT_ESPECIAL', 'abandono de los controles del CMAPA'],
      ['PERSONA', 'Moreno'],
      ['CAT_ESPECIAL', 'portadora del VIH'],
      ['CAT_ESPECIAL', 'negativo en las pruebas de transmisión vertical'],
      ['NORMA', 'artículo 177.2.2.º del Código Civil'],
      ['PERSONA', 'Ramón Albar Oliván'],
      ['PERSONA', 'Aitana Lanuza Marín'],
      ['LAJ', 'Jesús Ángel Sancho Pueyo'],
    ],
  },
  {
    id: 'e-filiacion-adn',
    fuente: 'Demanda de reclamación de filiación no matrimonial con proposición de prueba biológica',
    clase: 'nativo',
    texto: 'AL TRIBUNAL DE INSTANCIA DE MADRID, SECCIÓN DE FAMILIA, PLAZA QUE POR TURNO CORRESPONDA\n\nDoña Karla Julieth Montoya Restrepo, de nacionalidad colombiana, NIE Y5208913W, en nombre propio y en representación de su hijo menor Santiago Montoya Restrepo, nacido el 3 de agosto de 2021, con domicilio en calle de Bravo Murillo, 305, 7.º 2, 28020 Madrid, teléfono +34 611 208 754 y correo karla.montoya.r@outlook.com, interpone DEMANDA DE RECLAMACIÓN DE FILIACIÓN NO MATRIMONIAL contra don Enrique de Castro-Vallejo Urquijo, con domicilio en calle de Serrano, 112, 6.º, 28006 Madrid.\n\nHECHOS\n\nPRIMERO.- La actora y el demandado mantuvieron una relación sentimental entre octubre de 2019 y diciembre de 2020, conocida por el hermano del demandado, don Íñigo de Castro-Vallejo Urquijo, y por la empleada de hogar del demandado, doña Rosmery Huamán Ccori.\n\nSEGUNDO.- En 2024, una prueba de ADN privada, realizada con muestras de saliva del menor y de un vaso usado por el demandado, arrojó una probabilidad de paternidad del 99,997 %. Castro-Vallejo se negó a reconocer al niño y a someterse a una nueva prueba.\n\nTERCERO.- El menor presenta un trastorno del espectro autista de grado 1, por lo que se solicitan alimentos que cubran la terapia ocupacional.\n\nOTROSÍ DIGO: que se acuerde la práctica de la prueba biológica de paternidad por el Instituto Nacional de Toxicología y Ciencias Forenses (art. 767.4 LEC).',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE MADRID, SECCIÓN DE FAMILIA'],
      ['PERSONA', 'Karla Julieth Montoya Restrepo'],
      ['NIE', 'Y5208913W'],
      ['PERSONA', 'Santiago Montoya Restrepo'],
      ['DIRECCION', 'calle de Bravo Murillo, 305, 7.º 2, 28020 Madrid'],
      ['TELEFONO', '+34 611 208 754'],
      ['CORREO', 'karla.montoya.r@outlook.com'],
      ['PERSONA', 'Enrique de Castro-Vallejo Urquijo'],
      ['DIRECCION', 'calle de Serrano, 112, 6.º, 28006 Madrid'],
      ['PERSONA', 'Íñigo de Castro-Vallejo Urquijo'],
      ['PERSONA', 'Rosmery Huamán Ccori'],
      ['CAT_ESPECIAL', 'una prueba de ADN privada'],
      ['CAT_ESPECIAL', 'una probabilidad de paternidad del 99,997 %'],
      ['PERSONA', 'Castro-Vallejo'],
      ['CAT_ESPECIAL', 'un trastorno del espectro autista de grado 1'],
      ['CAT_ESPECIAL', 'terapia ocupacional'],
      ['CAT_ESPECIAL', 'prueba biológica de paternidad'],
      ['ORGANISMO', 'Instituto Nacional de Toxicología y Ciencias Forenses'],
      ['NORMA', 'art. 767.4 LEC'],
    ],
    ambiguo: ['Castro-Vallejo'],
  },
  {
    id: 'e-rectificacion-sexo',
    fuente: 'Solicitud de rectificación registral de la mención relativa al sexo (Ley 4/2023)',
    clase: 'nativo',
    texto: 'A L\'ENCARREGAT DEL REGISTRE CIVIL DE PALMA\nAL ENCARGADO DEL REGISTRO CIVIL DE PALMA\n\nDoña Aina Mas Coll, inscrita con el nombre de Antoni Mas Coll, con DNI 40287561W, nacida en Palma el 14 de marzo de 1996 y con domicilio en carrer de Blanquerna, 23, 2n, 07003 Palma, teléfono 871 03 22 64, SOLICITA, al amparo del artículo 44 de la Ley 4/2023, de 28 de febrero, la rectificación de la mención registral relativa al sexo y el cambio de nombre propio.\n\nManifiesta que se reconoce como mujer trans desde la adolescencia. Aunque la ley no lo exige, hace constar que sigue tratamiento hormonal con estradiol y ciproterona pautado por la Unidad de Identidad de Género del Hospital Universitario Son Espases, y que aporta, a los solos efectos de su propio archivo, un informe psicológico de 2023.\n\nComparecerán en la segunda comparecencia, a efectos de ratificación, sus amigos doña Joana Ferrer Amengual y don Biel Sastre Pons.\n\nPalma, 5 de septiembre de 2026.',
    oro: [
      ['ORGANISMO', 'REGISTRE CIVIL DE PALMA'],
      ['ORGANISMO', 'REGISTRO CIVIL DE PALMA'],
      ['PERSONA', 'Aina Mas Coll'],
      ['PERSONA', 'Antoni Mas Coll'],
      ['DNI', '40287561W'],
      ['DIRECCION', 'carrer de Blanquerna, 23, 2n, 07003 Palma'],
      ['TELEFONO', '871 03 22 64'],
      ['NORMA', 'artículo 44 de la Ley 4/2023, de 28 de febrero'],
      ['CAT_ESPECIAL', 'mujer trans'],
      ['CAT_ESPECIAL', 'tratamiento hormonal con estradiol y ciproterona'],
      ['ORGANISMO', 'Unidad de Identidad de Género del Hospital Universitario Son Espases'],
      ['CAT_ESPECIAL', 'informe psicológico'],
      ['PERSONA', 'Joana Ferrer Amengual'],
      ['PERSONA', 'Biel Sastre Pons'],
    ],
  },
  {
    id: 'e-contrato-trabajo',
    fuente: 'Contrato de trabajo indefinido a tiempo parcial (cláusulas iniciales y adicionales)',
    clase: 'nativo',
    texto: 'CONTRATO DE TRABAJO INDEFINIDO A TIEMPO PARCIAL\n\nEn Barcelona, a 1 de septiembre de 2026.\n\nREUNIDOS\n\nDe una parte, RESTAURANTE JARDÍN DE JADE, S.L., con CIF B66214586 y domicilio social en carrer de Pujades, 180, 08005 Barcelona, representada por su administrador único, don Zhang Xiaoming.\n\nY de otra, CHEN, Meiling, con NIE Y2839145Q, n.º de afiliación 08/2093154881, domiciliada en calle de Marina, 212, entresuelo 1.ª, 08013 Barcelona, teléfono 644870213.\n\nCLÁUSULAS\n\nPRIMERA.- La trabajadora prestará servicios como ayudante de cocina, grupo profesional 4 del Convenio colectivo de hostelería de Cataluña, 25 horas semanales.\n\nSEGUNDA.- El salario se abonará por transferencia a la cuenta ES3514650100939119876543.\n\nCLÁUSULAS ADICIONALES\n\n1.ª La trabajadora declara tener reconocida una discapacidad del 33 % por hipoacusia, a efectos de la bonificación de cuotas, y se compromete a pasar el reconocimiento médico de vigilancia de la salud.\n\n2.ª La trabajadora declara estar afiliada a UGT y autoriza el descuento en nómina de la cuota sindical.\n\n3.ª Persona de contacto en caso de emergencia: Chen Wei (hermano), 695 20 11 48.\n\nFirmado: Zhang Xiaoming — Chen Meiling',
    oro: [
      ['CIF', 'B66214586'],
      ['PERSONA', 'Zhang Xiaoming'],
      ['PERSONA', 'CHEN, Meiling'],
      ['NIE', 'Y2839145Q'],
      ['NUSS', '08/2093154881'],
      ['DIRECCION', 'calle de Marina, 212, entresuelo 1.ª, 08013 Barcelona'],
      ['TELEFONO', '644870213'],
      ['NORMA', 'Convenio colectivo de hostelería de Cataluña'],
      ['IBAN', 'ES3514650100939119876543'],
      ['CAT_ESPECIAL', 'una discapacidad del 33 % por hipoacusia'],
      ['CAT_ESPECIAL', 'reconocimiento médico de vigilancia de la salud'],
      ['CAT_ESPECIAL', 'afiliada a UGT'],
      ['CAT_ESPECIAL', 'la cuota sindical'],
      ['PERSONA', 'Chen Wei'],
      ['TELEFONO', '695 20 11 48'],
      ['PERSONA', 'Chen Meiling'],
    ],
  },
  {
    id: 'e-amonestacion',
    fuente: 'Carta de amonestación por escrito a un trabajador',
    clase: 'nativo',
    texto: 'HIERROS DEL EBRO, S.A. — CIF A28037158\nPolígono Malpica, calle E, parcela 12, 50016 Zaragoza\n\nD. PASTOR MORENO, Lorenzo\nDNI 14630597K — NAF 46/7201593470\nEntregada en mano\n\nZaragoza, 24 de septiembre de 2026\n\nMuy Sr. nuestro:\n\nPor medio de la presente le comunicamos que la Dirección ha decidido imponerle una AMONESTACIÓN POR ESCRITO por falta leve de puntualidad (art. 58 ET y art. 42.a del Convenio colectivo del sector del metal de Zaragoza), por los siguientes hechos:\n\nEl pasado 17 de septiembre, Pastor se incorporó al turno de mañana con 47 minutos de retraso, sin preaviso. Según el parte del jefe de turno, don Iván Sierra Gil, era la tercera vez en el mes. Sierra le requirió la justificación y usted alegó que venía de su sesión de psicoterapia, sin aportar justificante.\n\nLe recordamos que no está obligado a revelar el motivo de sus consultas médicas, pero sí a justificar la ausencia mediante el correspondiente documento.\n\nDada su condición de delegado sindical de CC. OO., se da traslado de la presente a la sección sindical y al comité de empresa.\n\nFdo.: Sergio Ballarín Lacasa, Director de Recursos Humanos.\n\nRecibí: Lorenzo Pastor (firma ilegible)',
    oro: [
      ['CIF', 'A28037158'],
      ['PERSONA', 'PASTOR MORENO, Lorenzo'],
      ['DNI', '14630597K'],
      ['NUSS', '46/7201593470'],
      ['NORMA', 'art. 58 ET'],
      ['NORMA', 'art. 42.a del Convenio colectivo del sector del metal de Zaragoza'],
      ['PERSONA', 'Pastor'],
      ['PERSONA', 'Iván Sierra Gil'],
      ['PERSONA', 'Sierra'],
      ['CAT_ESPECIAL', 'sesión de psicoterapia'],
      ['CAT_ESPECIAL', 'delegado sindical de CC. OO.'],
      ['PERSONA', 'Sergio Ballarín Lacasa'],
      ['PERSONA', 'Lorenzo Pastor'],
    ],
  },
  {
    id: 'e-aepd',
    fuente: 'Reclamación ante la Agencia Española de Protección de Datos por comunicación indebida de datos de salud',
    clase: 'nativo',
    texto: 'A LA AGENCIA ESPAÑOLA DE PROTECCIÓN DE DATOS\nC/ Jorge Juan, 6, 28001 Madrid\n\nRECLAMACIÓN\n\nReclamante: Ms. Siobhan Fletcher, NIE X9834102S, con domicilio en Avinguda del Pla, 126, bloque B, 03730 Xàbia. Correo: siobhan.fletcher@btinternet.com. Teléfono: +44 7700 900412.\n\nReclamada: CLÍNICA DENTAL MONTGÓ, S.L.P., CIF B91364802, con domicilio social en calle Doctor Fleming, 3, 03730 Jávea.\n\nHECHOS\n\n1. El 2 de julio de 2026 la recepcionista de la clínica, Noelia, envió por WhatsApp al teléfono de otro paciente, Mr. Graham Whitaker, mi radiografía panorámica y el presupuesto de mi tratamiento de implantes, en el que constaba que padezco periodontitis avanzada y alergia a la penicilina.\n\n2. El Sr. Whitaker, vecino de mi urbanización, me reenvió los documentos y me dijo que también le habían enviado, por error, el odontograma de otra paciente, una tal Mrs. Pamela Hughes.\n\n3. El delegado de protección de datos de la clínica, don Marcos Llorca Signes (dpd@clinicamontgo.es), me respondió que se trataba de «un error humano sin consecuencias».\n\nSe invoca la infracción de los artículos 5.1.f) y 9 del RGPD y 32 de la LOPDGDD.',
    oro: [
      ['ORGANISMO', 'AGENCIA ESPAÑOLA DE PROTECCIÓN DE DATOS'],
      ['PERSONA', 'Siobhan Fletcher'],
      ['NIE', 'X9834102S'],
      ['DIRECCION', 'Avinguda del Pla, 126, bloque B, 03730 Xàbia'],
      ['CORREO', 'siobhan.fletcher@btinternet.com'],
      ['TELEFONO', '+44 7700 900412'],
      ['CIF', 'B91364802'],
      ['PERSONA', 'Noelia'],
      ['PERSONA', 'Graham Whitaker'],
      ['CAT_ESPECIAL', 'radiografía panorámica'],
      ['CAT_ESPECIAL', 'tratamiento de implantes'],
      ['CAT_ESPECIAL', 'periodontitis avanzada y alergia a la penicilina'],
      ['PERSONA', 'Whitaker'],
      ['CAT_ESPECIAL', 'odontograma'],
      ['PERSONA', 'Pamela Hughes'],
      ['PERSONA', 'Marcos Llorca Signes'],
      ['CORREO', 'dpd@clinicamontgo.es'],
      ['NORMA', 'artículos 5.1.f) y 9 del RGPD'],
    ],
  },
  {
    id: 'e-sms-caida',
    fuente: 'SMS entre hermanos transcritos en una reclamación a la comunidad de propietarios por caída',
    clase: 'nativo',
    texto: 'DOCUMENTO N.º 2 — Transcripción de SMS entre don José María Gallardo Pinto («Chema») y su hermana doña María Isabel Gallardo Pinto («Maribel»), 11 de marzo de 2026.\n\n18:02 Chema: Maribel mamá se ha caído en el portal, el escalón roto otra vez\n18:03 Maribel: dios mío dónde estáis\n18:10 Chema: en el Gregorio Marañón, dicen q tiene rota la cadera, la operan mañana\n18:11 Maribel: aviso a Quique y a la Pili\n18:25 Chema: el presidente, el Tomás del 3.º, ya sabía lo del escalón desde enero\n18:27 Maribel: díselo al administrador, el tal Arteaga, su móvil es 699 44 22 11\n18:40 Chema: mamá dice q no le digas nada a la tía Pura q está con la tensión alta y el sintrom\n\nLa perjudicada es doña Encarnación Pinto Robles, de 84 años, vecina del inmueble de la calle del Doctor Esquerdo, 170, 28007 Madrid.',
    oro: [
      ['PERSONA', 'José María Gallardo Pinto'],
      ['PERSONA', 'Chema'],
      ['PERSONA', 'María Isabel Gallardo Pinto'],
      ['PERSONA', 'Maribel'],
      ['ORGANISMO', 'Gregorio Marañón'],
      ['CAT_ESPECIAL', 'rota la cadera'],
      ['CAT_ESPECIAL', 'la operan mañana'],
      ['PERSONA', 'Quique'],
      ['PERSONA', 'Pili'],
      ['PERSONA', 'Tomás'],
      ['PERSONA', 'Arteaga'],
      ['TELEFONO', '699 44 22 11'],
      ['PERSONA', 'Pura'],
      ['CAT_ESPECIAL', 'la tensión alta y el sintrom'],
      ['PERSONA', 'Encarnación Pinto Robles'],
      ['DIRECCION', 'calle del Doctor Esquerdo, 170, 28007 Madrid'],
    ],
  },
  {
    id: 'e-nota-manuscrita',
    fuente: 'Nota manuscrita de una llamada, escaneada con OCR',
    clase: 'ocr',
    texto: 'NOTA LLAMADA 23/9 - 10:40\nSRA. MARIA JOSE GIL (HIJA DE D. ANSELMO GIL ORTUNO) TEL 616 88 02 41\nDICE Q SU PADRE TIENE ALZHEIMER AVANZADO (GDS 6) Y Q EL HERMANO, RAMIRO, LE HIZO FIRMAR UN PODER EN LA NOTARIA DEL SR. ARIZMENDI EN MAYO.\nRAMIRO TIENE DEUDAS DE JUEGO - LUDOPATIA?? - Y ESTUVO EN LA CARCEL DE DAROCA EN 2018.\nPEDIR HISTORIA CLINICA DEL C.S. SAN JOSE NORTE.\nDNI PADRE 21749836R\nDOMIC. AVDA. CESAR AUGUSTO 61 3 B ZARAGOZA\nPROX. PASO: MEDIDAS DE APOYO - T. INSTANCIA ZARAGOZA SECC. CIVIL\nLLAMAR A MARIAJO JUEVES',
    oro: [
      ['PERSONA', 'MARIA JOSE GIL'],
      ['PERSONA', 'ANSELMO GIL ORTUNO'],
      ['TELEFONO', '616 88 02 41'],
      ['CAT_ESPECIAL', 'ALZHEIMER AVANZADO (GDS 6)'],
      ['PERSONA', 'RAMIRO'],
      ['PERSONA', 'ARIZMENDI'],
      ['CAT_ESPECIAL', 'LUDOPATIA'],
      ['DATO_PENAL', 'ESTUVO EN LA CARCEL DE DAROCA EN 2018'],
      ['CAT_ESPECIAL', 'HISTORIA CLINICA'],
      ['ORGANISMO', 'C.S. SAN JOSE NORTE'],
      ['DNI', '21749836R'],
      ['DIRECCION', 'AVDA. CESAR AUGUSTO 61 3 B ZARAGOZA'],
      ['ORGANO', 'T. INSTANCIA ZARAGOZA SECC. CIVIL'],
      ['PERSONA', 'MARIAJO'],
    ],
  },
  {
    id: 'e-constitucion-sl',
    fuente: 'Escritura de constitución de sociedad limitada con tres socios personas físicas',
    clase: 'nativo',
    texto: 'NÚMERO MIL TRESCIENTOS DOCE.\nESCRITURA DE CONSTITUCIÓN DE SOCIEDAD DE RESPONSABILIDAD LIMITADA\n\nEn Las Palmas de Gran Canaria, a quince de septiembre de dos mil veintiséis.\n\nAnte mí, AGUSTÍN RUIZ DE ALDA MACHÍN, Notario del Ilustre Colegio de Canarias, con residencia en esta capital,\n\nCOMPARECEN\n\nDON KLAUS-DIETER HOFFMANN, mayor de edad, de nacionalidad alemana, casado en régimen de separación de bienes conforme a su ley nacional, con domicilio en calle Pedro del Castillo Westerling, 7, 3.º B, 35007 Las Palmas de Gran Canaria, y NIE Y8452016J.\n\nMR. OLIVER JAMES WHITMORE, mayor de edad, de nacionalidad británica, soltero, domiciliado en calle Timanfaya, 22, Urbanización Playa del Águila, 35290 San Bartolomé de Tirajana, y NIE Z3067291Q. Interviene con asistencia de la intérprete jurada doña Beatriz Quintana Ojeda.\n\nDON YERAY CABRERA DÉNIZ, mayor de edad, soltero, vecino de Las Palmas de Gran Canaria, con domicilio en calle Galileo, 45, Tafira Alta, 35017 Las Palmas de Gran Canaria, y DNI 50274639C.\n\nOTORGAN\n\nPRIMERO.- Constituyen la sociedad ATLANTIC SURF LAB, S.L., con domicilio social en calle Alcalde Ramírez Bethencourt, 8, 35003 Las Palmas de Gran Canaria, y NIF provisional B35749266.\n\nSEGUNDO.- El capital social de 12.000 euros se desembolsa íntegramente: Hoffmann suscribe 5.000 participaciones, Whitmore 4.000 y Cabrera 3.000, según certificación de depósito en la cuenta ES97 3058 0990 2927 2101 2345 abierta a nombre de la sociedad en constitución.\n\nTERCERO.- Se nombra administrador único a Mr. Oliver James Whitmore, por plazo indefinido, quien acepta.\n\nLeída por mí, el Notario, la presente escritura, la firman conmigo. Doy fe.',
    oro: [
      ['PERSONA', 'AGUSTÍN RUIZ DE ALDA MACHÍN'],
      ['ORGANISMO', 'Ilustre Colegio de Canarias'],
      ['PERSONA', 'KLAUS-DIETER HOFFMANN'],
      ['DIRECCION', 'calle Pedro del Castillo Westerling, 7, 3.º B, 35007 Las Palmas de Gran Canaria'],
      ['NIE', 'Y8452016J'],
      ['PERSONA', 'OLIVER JAMES WHITMORE'],
      ['DIRECCION', 'calle Timanfaya, 22, Urbanización Playa del Águila, 35290 San Bartolomé de Tirajana'],
      ['NIE', 'Z3067291Q'],
      ['PERSONA', 'Beatriz Quintana Ojeda'],
      ['PERSONA', 'YERAY CABRERA DÉNIZ'],
      ['DIRECCION', 'calle Galileo, 45, Tafira Alta, 35017 Las Palmas de Gran Canaria'],
      ['DNI', '50274639C'],
      ['CIF', 'B35749266'],
      ['PERSONA', 'Hoffmann'],
      ['PERSONA', 'Whitmore'],
      ['PERSONA', 'Cabrera'],
      ['IBAN', 'ES97 3058 0990 2927 2101 2345'],
      ['PERSONA', 'Oliver James Whitmore'],
    ],
  },
  {
    id: 'e-poder-pleitos',
    fuente: 'Escritura de poder general para pleitos',
    clase: 'nativo',
    texto: 'PODER GENERAL PARA PLEITOS\n\nNúmero ochocientos cuarenta y siete.\nEn Vila-real, a diez de septiembre de dos mil veintiséis.\n\nAnte mí, VICENTE CERVERA BELTRÁN, Notario del Ilustre Colegio de Valencia, con residencia en Vila-real,\n\nCOMPARECE: DON IONUȚ-ALEXANDRU POPESCU, mayor de edad, casado, de nacionalidad rumana, con domicilio en calle Mayor, 88, 2.º, 12540 Vila-real, y NIE Y3170482S. Asiste, a efectos de prestar su consentimiento en lo que afecta a la vivienda familiar, su esposa, DOÑA ANDREEA POPESCU, con NIE X3391576L.\n\nINTERVIENE en su propio nombre y OTORGA poder general para pleitos, tan amplio como en Derecho se requiera, a favor de:\n\n— Los Procuradores de los Tribunales doña María Dolores Ventura Segarra y don Pascual Cabedo Nebot, de los Colegios de Castellón y Valencia.\n— El Abogado don Héctor Rubio Gimeno, del Ilustre Colegio de la Abogacía de Castellón.\n\nPara que, indistintamente, representen al Sr. Popescu ante cualesquiera juzgados, tribunales, Tribunales de Instancia, Audiencias, Tribunal Supremo y Tribunal Constitucional, incluso para absolver posiciones y transigir.\n\nYo, el Notario, doy fe de que el otorgante, a quien identifico por su documento, tiene a mi juicio capacidad suficiente.',
    oro: [
      ['PERSONA', 'VICENTE CERVERA BELTRÁN'],
      ['ORGANISMO', 'Ilustre Colegio de Valencia'],
      ['PERSONA', 'IONUȚ-ALEXANDRU POPESCU'],
      ['DIRECCION', 'calle Mayor, 88, 2.º, 12540 Vila-real'],
      ['NIE', 'Y3170482S'],
      ['PERSONA', 'ANDREEA POPESCU'],
      ['NIE', 'X3391576L'],
      ['PERSONA', 'María Dolores Ventura Segarra'],
      ['PERSONA', 'Pascual Cabedo Nebot'],
      ['PERSONA', 'Héctor Rubio Gimeno'],
      ['ORGANISMO', 'Ilustre Colegio de la Abogacía de Castellón'],
      ['PERSONA', 'Popescu'],
    ],
  },

  // ───────────────────────── EXPEDIENTE: finca ocupada en Sóller (von der Heide) ─────────────────────────
  {
    id: 'e-soller-correo',
    fuente: 'Correo de una clienta alemana al despacho sobre su finca ocupada',
    clase: 'correo',
    expediente: 'exp-soller-vonderheide',
    texto: 'From: Annegret von der Heide <annegret.vdheide@t-online.de>\nTo: tomeu@arbonaadvocats.es\nSubject: Finca Can Bleda - Hilfe!!\nDate: Mon, 14 Sep 2026 09:17:44 +0200\n\nLieber Tomeu,\n\nperdone mi español. Mi vecina Francisca me ha dicho que hay gente viviendo en la casa de Sóller, Camí de Can Bleda, 18, desde agosto. Yo no puedo viajar ahora: tengo un cáncer de mama y estoy en quimioterapia en el UKE de Hamburgo hasta noviembre.\n\nLa casa era de mi marido, el Dr. Wolfgang von der Heide, que murió en 2023; la herencia ya está inscrita a mi nombre y al de mi hijo Jan-Hendrik.\n\nPor favor, pida al notario que vaya a ver. Le transfiero la provisión desde mi cuenta española ES52 0075 0125 4417 0654 3210.\n\nMein Telefon: +49 40 3861 2274\n\nViele Grüße\nAnnegret',
    oro: [
      ['PERSONA', 'Annegret von der Heide'],
      ['CORREO', 'annegret.vdheide@t-online.de'],
      ['CORREO', 'tomeu@arbonaadvocats.es'],
      ['PERSONA', 'Tomeu'],
      ['PERSONA', 'Francisca'],
      ['DIRECCION', 'Camí de Can Bleda, 18'],
      ['CAT_ESPECIAL', 'un cáncer de mama'],
      ['CAT_ESPECIAL', 'quimioterapia'],
      ['ORGANISMO', 'UKE de Hamburgo'],
      ['PERSONA', 'Wolfgang von der Heide'],
      ['PERSONA', 'Jan-Hendrik'],
      ['IBAN', 'ES52 0075 0125 4417 0654 3210'],
      ['TELEFONO', '+49 40 3861 2274'],
      ['PERSONA', 'Annegret'],
    ],
  },
  {
    id: 'e-soller-acta-presencia',
    fuente: 'Acta notarial de presencia en vivienda ocupada',
    clase: 'nativo',
    expediente: 'exp-soller-vonderheide',
    texto: 'ACTA DE PRESENCIA\n\nNúmero seiscientos dos.\nEn Sóller, a diecisiete de septiembre de dos mil veintiséis, a las once horas.\n\nYo, BERNAT JAUME ALCOVER ROSSELLÓ, Notario del Ilustre Colegio de las Illes Balears, con residencia en Sóller, a requerimiento de don Bartomeu Arbona Mayol, abogado, que actúa en nombre de doña Annegret von der Heide según poder que exhibe, me constituyo en la vivienda sita en Camí de Can Bleda, número 18, 07100 Sóller.\n\nHAGO CONSTAR:\n\n1. Que la cerradura de la puerta principal ha sido sustituida. Llamo y abre un varón que dice llamarse Kevin Alexis Guzmán Rojas y no exhibe documento alguno. Manifiesta que vive allí con su pareja, que se encuentra embarazada de siete meses, y con un menor de corta edad, y que pagó 600 euros a «un tal Sebas» por las llaves.\n\n2. Que en el patio está estacionado un turismo con matrícula 1297 LZB.\n\n3. Que la vecina de la finca colindante, doña Francisca Coll Bibiloni, me manifiesta que los ocupantes llegaron en agosto y que el varón le dijo que había salido de la cárcel hacía poco.\n\n4. Que el Sr. Guzmán se niega a que se tomen fotografías del interior.\n\nDe todo lo cual, y de que el requirente, don Tomeu Arbona, queda enterado, yo, el Notario, doy fe.',
    oro: [
      ['PERSONA', 'BERNAT JAUME ALCOVER ROSSELLÓ'],
      ['ORGANISMO', 'Ilustre Colegio de las Illes Balears'],
      ['PERSONA', 'Bartomeu Arbona Mayol'],
      ['PERSONA', 'Annegret von der Heide'],
      ['DIRECCION', 'Camí de Can Bleda, número 18, 07100 Sóller'],
      ['PERSONA', 'Kevin Alexis Guzmán Rojas'],
      ['CAT_ESPECIAL', 'embarazada de siete meses'],
      ['PERSONA', 'Sebas'],
      ['MATRICULA', '1297 LZB'],
      ['PERSONA', 'Francisca Coll Bibiloni'],
      ['DATO_PENAL', 'había salido de la cárcel hacía poco'],
      ['PERSONA', 'Guzmán'],
      ['PERSONA', 'Tomeu Arbona'],
    ],
  },
  {
    id: 'e-pericial-caligrafica',
    fuente: 'Informe pericial caligráfico sobre la firma de un pagaré',
    clase: 'nativo',
    texto: 'INFORME PERICIAL CALIGRÁFICO\n\nTribunal de Instancia de Valladolid, Sección Civil, Plaza n.º 2 — Juicio cambiario 233/2026\n\nPerita: Esperanza Toledo Sierra, licenciada en Criminología, perita calígrafa judicial, con despacho en calle de Santiago, 19, 2.º, 47001 Valladolid, tel. 983 35 71 20, designada por insaculación.\n\nOBJETO: determinar si la firma que figura en el pagaré de 45.000 euros librado a favor de INVERSIONES PISUERGA 2020, S.L. fue estampada por don Gregorio Baños Espinosa.\n\nDOCUMENTOS INDUBITADOS: firma del DNI 08715243Z expedido en 2015; escritura de compraventa de 2019; cuerpo de escritura realizado ante la LAJ el 3 de junio de 2026.\n\nANÁLISIS: la firma dubitada presenta temblor de ejecución y paradas anómalas. El Sr. Baños padece enfermedad de Parkinson diagnosticada en 2021, según el informe neurológico unido a autos, lo que explica el temblor de las firmas indubitadas posteriores a esa fecha, pero no la inclinación dextrógira ni el ataque en gancho de la dubitada.\n\nDISCREPANCIA CON EL INFORME DE PARTE: el perito de la actora, don Lucas Sierra Montes, trabajó sobre fotocopia. Sierra no examinó el original, por lo que sus conclusiones sobre presión del trazo carecen de base.\n\nCONCLUSIÓN: la firma dubitada NO ha sido realizada por el puño y letra de don Gregorio Baños Espinosa (probabilidad alta).\n\nValladolid, 16 de septiembre de 2026. Fdo.: Esperanza Toledo Sierra.',
    oro: [
      ['ORGANO', 'Tribunal de Instancia de Valladolid, Sección Civil, Plaza n.º 2'],
      ['AUTOS', 'Juicio cambiario 233/2026'],
      ['PERSONA', 'Esperanza Toledo Sierra'],
      ['TELEFONO', '983 35 71 20'],
      ['PERSONA', 'Gregorio Baños Espinosa'],
      ['DNI', '08715243Z'],
      ['PERSONA', 'Baños'],
      ['CAT_ESPECIAL', 'enfermedad de Parkinson diagnosticada en 2021'],
      ['CAT_ESPECIAL', 'informe neurológico'],
      ['PERSONA', 'Lucas Sierra Montes'],
      ['PERSONA', 'Sierra'],
    ],
    ambiguo: ['Sierra'],
  },
  {
    id: 'e-tasacion',
    fuente: 'Informe de tasación hipotecaria escaneado',
    clase: 'ocr',
    texto: 'TASACIONES CANTABRICO SA - C/ CALVO SOTELO 19 39002 SANTANDER - INSCRITA EN EL REGISTRO DEL BANCO DE ESPANA CON EL N. 4471\nINFORME DE TASACION N. 26-04471-RS\n\nSOLICITANTE: GUTIERREZ DEL CAMPO, JOSE MANUEL - TFNO 942 23 90 18\nFINALIDAD: GARANTIA HIPOTECARIA (ORDEN ECO/805/2003)\n\nIDENTIFICACION DEL INMUEBLE: VIVIENDA EN CL MARQUES DE LA HERMIDA 41 3 IZ 39009 SANTANDER\nREF. CATASTRAL: 5721403VP3152A0012KL\nFINCA REGISTRAL 23.118 DEL REGISTRO DE LA PROPIEDAD N. 4 DE SANTANDER\n\nTITULARES REGISTRALES:\n- GUTIERREZ DEL CAMPO, JOSE MANUEL (50 %) - DNI 39516824H\n- ABASCAL REVUELTA, MARIA LUZ (50 %) - DNI 05713962A\n\nOCUPACION: OCUPADA POR LA TITULAR MARIA LUZ ABASCAL, QUE SE DESPLAZA EN SILLA DE RUEDAS POR UNA ESCLEROSIS MULTIPLE; EL EDIFICIO CARECE DE ASCENSOR ADAPTADO.\n\nVALOR DE TASACION: 214.600,00 EUR\n\nTECNICO: IGNACIO REVUELTA PORTILLA - ARQUITECTO TECNICO COLEG. 1.187',
    oro: [
      ['ORGANISMO', 'BANCO DE ESPANA'],
      ['PERSONA', 'GUTIERREZ DEL CAMPO, JOSE MANUEL'],
      ['TELEFONO', '942 23 90 18'],
      ['NORMA', 'ORDEN ECO/805/2003'],
      ['DIRECCION', 'CL MARQUES DE LA HERMIDA 41 3 IZ 39009 SANTANDER'],
      ['ORGANISMO', 'REGISTRO DE LA PROPIEDAD N. 4 DE SANTANDER'],
      ['DNI', '39516824H'],
      ['PERSONA', 'ABASCAL REVUELTA, MARIA LUZ'],
      ['DNI', '05713962A'],
      ['PERSONA', 'MARIA LUZ ABASCAL'],
      ['CAT_ESPECIAL', 'SILLA DE RUEDAS'],
      ['CAT_ESPECIAL', 'UNA ESCLEROSIS MULTIPLE'],
      ['PERSONA', 'IGNACIO REVUELTA PORTILLA'],
    ],
  },
  {
    id: 'e-precario',
    fuente: 'Demanda de desahucio por precario contra los antiguos cuidadores de la causante',
    clase: 'nativo',
    texto: 'AL TRIBUNAL DE INSTANCIA DE MADRID, SECCIÓN CIVIL, PLAZA QUE POR REPARTO CORRESPONDA\n\nDon Ignacio Argüelles de la Cuesta, Procurador de los Tribunales, en nombre de DON EMILIO SÁNCHEZ LUNA y DOÑA PILAR SÁNCHEZ LUNA, herederos de doña Remedios Luna Bermejo, bajo la dirección de la letrada doña Cristina Villaverde Oña, interpone DEMANDA DE JUICIO VERBAL DE DESAHUCIO POR PRECARIO (art. 250.1.2.º LEC) contra:\n\n— QUISPE MAMANI, Wilmer Andrés, y\n— CHOQUE CONDORI, Yolanda,\n\nambos con domicilio en la vivienda objeto del pleito, calle Nuestra Señora de Fátima, 27, bajo B, 28047 Madrid.\n\nHECHOS\n\nPRIMERO.- Los demandados cuidaron de doña Remedios desde 2021 hasta su fallecimiento el 30 de abril de 2026. La causante padecía demencia senil y les permitió vivir en la vivienda a cambio de sus cuidados, sin renta alguna.\n\nSEGUNDO.- Fallecida la causante, los Sres. Sánchez Luna requirieron a los demandados el desalojo por burofax de 2 de junio de 2026, sin resultado. Wilmer respondió por WhatsApp que «la señora nos la dejó de palabra».\n\nTERCERO.- Consta a esta parte que en la vivienda residen dos hijos menores de los demandados, uno de ellos con parálisis cerebral, por lo que se interesa que se dé traslado a los servicios sociales del Ayuntamiento de Madrid (art. 441.5 LEC).\n\nSUPLICO se dicte sentencia declarando haber lugar al desahucio.',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE MADRID, SECCIÓN CIVIL'],
      ['PERSONA', 'Ignacio Argüelles de la Cuesta'],
      ['PERSONA', 'EMILIO SÁNCHEZ LUNA'],
      ['PERSONA', 'PILAR SÁNCHEZ LUNA'],
      ['PERSONA', 'Remedios Luna Bermejo'],
      ['PERSONA', 'Cristina Villaverde Oña'],
      ['NORMA', 'art. 250.1.2.º LEC'],
      ['PERSONA', 'QUISPE MAMANI, Wilmer Andrés'],
      ['PERSONA', 'CHOQUE CONDORI, Yolanda'],
      ['DIRECCION', 'calle Nuestra Señora de Fátima, 27, bajo B, 28047 Madrid'],
      ['PERSONA', 'Remedios'],
      ['CAT_ESPECIAL', 'demencia senil'],
      ['PERSONA', 'Sánchez Luna'],
      ['PERSONA', 'Wilmer'],
      ['CAT_ESPECIAL', 'parálisis cerebral'],
      ['ORGANISMO', 'Ayuntamiento de Madrid'],
      ['NORMA', 'art. 441.5 LEC'],
    ],
    ambiguo: ['Sánchez Luna'],
  },
  {
    id: 'e-ejecucion-familia',
    fuente: 'Demanda ejecutiva de sentencia de divorcio con petición de suspensión de visitas',
    clase: 'nativo',
    texto: 'AL TRIBUNAL DE INSTANCIA DE LOGROÑO, SECCIÓN DE FAMILIA, PLAZA N.º 1\nDivorcio contencioso 402/2023\n\nDoña Sonia Calzada Rey, con DNI 63158720F y domicilio en calle Vara de Rey, 54, 1.º A, 26002 Logroño, representada por la procuradora doña Nerea Garrido Oteo, formula DEMANDA EJECUTIVA contra don Fernando Casado Barco, con domicilio en avenida de la Paz, 11, 5.º C, 26004 Logroño.\n\nPRIMERO.- La sentencia de 20 de marzo de 2024 fijó una pensión de alimentos de 350 euros por cada uno de los hijos, Lucía y Mateo Casado Calzada, a ingresar en la cuenta ES65 0081 7011 1211 0023 4567. Se adeudan 4.200 euros.\n\nSEGUNDO.- Casado ha perdido su empleo por su ludopatía, reconocida por él mismo en el Punto de Encuentro Familiar, y durante las visitas de agosto llevó a los menores a un salón de juego de la calle Marqués de Vallejo, como consta en el informe de la psicóloga doña Leire Ochoa Sáenz.\n\nTERCERO.- Calzada ha tenido que pedir un préstamo a su madre, doña Carmen Rey Ezquerro, para pagar el comedor escolar. Mateo, además, tiene asma y precisa un inhalador que el padre no le administra durante las visitas.\n\nSUPLICO se despache ejecución por 4.200 euros más 1.260 de intereses y costas, y se suspenda cautelarmente el régimen de visitas con pernocta.\n\nTel. de contacto de la ejecutante: 941 25 60 83 / 690 318 422.',
    oro: [
      ['ORGANO', 'TRIBUNAL DE INSTANCIA DE LOGROÑO, SECCIÓN DE FAMILIA, PLAZA N.º 1'],
      ['AUTOS', 'Divorcio contencioso 402/2023'],
      ['PERSONA', 'Sonia Calzada Rey'],
      ['DNI', '63158720F'],
      ['DIRECCION', 'calle Vara de Rey, 54, 1.º A, 26002 Logroño'],
      ['PERSONA', 'Nerea Garrido Oteo'],
      ['PERSONA', 'Fernando Casado Barco'],
      ['DIRECCION', 'avenida de la Paz, 11, 5.º C, 26004 Logroño'],
      ['PERSONA', 'Lucía'],
      ['PERSONA', 'Mateo Casado Calzada'],
      ['IBAN', 'ES65 0081 7011 1211 0023 4567'],
      ['PERSONA', 'Casado'],
      ['OBJETO', 'ludopatía'],
      ['ORGANISMO', 'Punto de Encuentro Familiar'],
      ['PERSONA', 'Leire Ochoa Sáenz'],
      ['PERSONA', 'Calzada'],
      ['PERSONA', 'Carmen Rey Ezquerro'],
      ['PERSONA', 'Mateo'],
      ['CAT_ESPECIAL', 'asma'],
      ['CAT_ESPECIAL', 'un inhalador'],
      ['TELEFONO', '941 25 60 83'],
      ['TELEFONO', '690 318 422'],
    ],
  },
];
