// Léxico de nombres de pila. Una LISTA, no un modelo: la v1 va sin modelo (Juan, 26-sep).
//
// Por qué hace falta. El corpus escrito a ciegas el 29-sep destapó lo que ninguna regla de
// contexto coge: el nombre de pila SOLO, como se nombra a la gente en un correo o en un informe
// psicosocial —«Me llamó ayer Garbiñe», «Hablé con Iñaki y con Maite», «Mi cuñado Toño», «Irene,
// de 11 años»—, y el nombre de pila más un apellido que la regla del nombre completo no veía
// porque el apellido coincide con una institución («Rocío Justicia Moreno») o porque son solo dos
// piezas («Jon Ugalde», «Olga Semenova»).
//
// Los nombres están en mayúsculas y sin tildes, que es como se comparan (ver texto.mjs).
//
// AMBIGUOS: los nombres que son también una palabra corriente o un lugar («Rosa», «Pilar»,
// «Mercedes», «Santiago», «Victoria», «Salvador»). Solos, se dejan pasar salvo que el contexto
// diga que son una persona —un saludo, un «mi hermana», una cabecera de correo—: es la regla de
// Juan para lo que no es categoría especial, en la duda se deja pasar.

const HOMBRES = `
AARON ABDEL ABDUL ABEL ABRAHAM ADAM ADAN ADEL ADOLFO ADRIA ADRIAN AGUSTI AGUSTIN AHMED AIMAR AITOR AITZOL ALAIN
ALBERT ALBERTO ALEIX ALEJANDRO ALEJO ALEKSANDR ALEX ALEXANDER ALEXANDRE ALEXIS ALFONSO ALFREDO ALI ALOIS ALONSO
ALVARO AMADEO AMADOR AMANCIO AMARO AMBROSIO AMETS ANDER ANDONI ANDRES ANDREU ANDREA ANDRZEJ ANGEL ANSELMO ANTONI
ANTONIO ANTXON ANXO APOLINAR ARIEL ARITZ ARKAITZ ARMANDO ARNAU ARNALDO ARSENIO ARTEM ARTUR ARTURO ASIER AURELIO
AUSIAS BALTASAR BARTOLOME BASILIO BAUTISTA BEÑAT BENITO BENJAMIN BERNAT BERNARDINO BERNARDO BIEL BLAS BONIFACIO BORJA
BRAIS BRUNO CAETANO CANDIDO CARLES CARLOS CARMELO CASIMIRO CAYETANO CECILIO CELESTINO CESAR CHEMA CHIDI CIPRIANO
CIRILO CLAUDIO COSME CRISTIAN CRISTOBAL CRISTOFOL DAMIAN DANI DANIEL DARIO DAVID DEMETRIO DENIS DESIDERIO DIDAC DIEGO
DIONISIO DMITRI DOMINGO DONATO EDGAR EDGARDO EDUARD EDUARDO EFREN EGOITZ EKAITZ ELADIO ELIAS ELISEO EMILIANO EMILIO
ENEKO ENRIC ENRIQUE ERIC ERIK ERNESTO ESTANISLAO ESTEBAN ESTEVE EUGENIO EUSEBIO EVARISTO EZEQUIEL FABIAN FABIO FAUSTINO
FAUSTO FEDERICO FELICIANO FELIPE FELIX FERMIN FERNANDO FERRAN FIDEL FILOMENO FLORENCIO FLORENTINO FRANCESC FRANCISCO
FRANCO FRANK FRAN FULGENCIO GABRIEL GAIZKA GARIKOITZ GASPAR GENARO GERARD GERARDO GERMAN GERVASIO GIL GINES GONZALO
GORKA GREGORIO GUILLE GUILLEM GUILLERMO GUSTAVO HANS HASSAN HECTOR HERMENEGILDO HERNAN HILARIO HORACIO HUGO HUMBERTO
IAGO IBAI IGNACIO IGNASI IGOR IKER IMANOL INAKI IÑAKI IÑIGO INIGO ISAAC ISAIAS ISIDORO ISIDRO ISMAEL ISRAEL IVAN IZAN
JACINTO JACOBO JAIME SANTIAGO SALVADOR DOMINGO ANGEL JESUS JAIRO JAUME JAVI JAVIER JEAN JENARO JEREMIAS JERONIMO JESUS JOAN JOAQUIM JOAQUIN JOEL JON JONATHAN
JORDI JORGE JOSE JOSEBA JOSEP JOSU JUAN JUANJO JULEN JULIAN JULIO JUSTINO KARIM KEPA KEVIN KHALID KIKE KOLDO LAUREANO
LAUREANO LAUTARO LAZARO LEANDRO LEOCADIO LEONARDO LEONCIO LEOPOLDO LLORENÇ LLORENC LLUIS LORENZO LUCAS LUCIANO LUIS
LUKAS MAMADOU MANEL MANOLO MANU MANUEL MARC MARCELINO MARCELO MARCIAL MARCO MARCOS MARIANO MARIO MARIUS MARTI MARTIN
MATEO MATIAS MAURICIO MAXIMILIANO MAXIMO MELCHOR MICHAEL MIGUEL MIGUELANGEL MIKEL MIQUEL MIRCEA MOHAMED MOHAMMED
MOHAMMAD MOISES MUSTAFA NACHO NARCISO NATALIO NAZARIO NESTOR NICANOR NICOLAS NIL NOE NORBERTO OCTAVIO ODON OLEGARIO
OLIVER OMAR ORIOL OSCAR OSVALDO OTTO OUSMANE OXEL PABLO PACO PAOLO PASCUAL PATRICIO PATXI PAU PAUL PAULINO PEDRO PELAYO
PEPE PERE PETER PIERRE PIOTR PLACIDO POL PRUDENCIO QUIQUE QUIM RAFA RAFAEL RAIMUNDO RAMIRO RAMON RAUL REINALDO REMIGIO
RENATO RICARD RICARDO ROBERT ROBERTO RODOLFO RODRIGO ROGELIO ROGER ROLANDO ROMAN ROMUALDO RUBEN RUFINO SAID SALVA
SAMUEL SANTI SATURNINO SAUL SEBASTIAN SEGUNDO SERAFIN SERGI SERGIO SEVERIANO SILVESTRE SILVIO SIMON SIXTO SOUFIANE
TEODORO TEOFILO TIBURCIO TIMOTEO TOMAS TONI TOÑO TONO TXEMA UNAI URBANO URKO VALENTIN VALERIANO VALERIO VENANCIO
VICENT VICENTE VICTOR VICTORIANO VIRGILIO VLADIMIR WALTER WILLIAM XABI XABIER XAVI XAVIER XOAN XOSE XURXO YAGO YERAY
YOUSSEF YUSUF ZACARIAS WILMER EDWIN JHONATAN ALEXANDRU IONUT GRAHAM MICHAEL PATRICK SEAN KEVIN NEIL IAN BRIAN WOLFGANG DIETER HELMUT UWE JENS TOMEU SEBAS RO QUIM JAUME BIEL PEP PEPE CHEMA NACHO PACO LOLO MANOLO KIKE RAFA TXUS TXETXU JOSEMA JUANMA JOSELU CHUS NEL XUAN PELAYO XIANA XOEL BREIXO BRAIS ROI UXIO ANTIA IAGO XACOBE ANXO ENEKO
JOSEBA IBON JOSU UNAI XABIER MIKEL ANDONI ENDIKA GAIZKA IÑIGO KOLDO KOLDOBIKA LUKEN OIER ERIK EKAITZ HARKAITZ
BJÖRN BJORN SVEN LARS OLAF KLAUS JÜRGEN JURGEN STEFAN THOMAS JOHN JAMES DAVID GEORGE HENRY JACK HARRY OLIVER
LUCA MATTEO GIUSEPPE FRANCESCO GIOVANNI PIETRO MARCO LORENZO ANDREI SERGIU IONUT MIHAI CRISTIAN VASILE GHEORGHE
DMITRY IVAN SERGEY ALEKSEI NIKOLAI YURI OLEKSANDR TARAS BOGDAN HAO WEI JUN MING LEI YONG JIAN XIAOMING
ABDELKADER ABDELLAH HAMID RACHID KHALID NOUREDDINE YASSINE AYOUB ISMAIL ANAS BILAL AMINE HICHAM MOUSSA ALIOU
OUMAR IBRAHIMA CHEIKH MODOU LAMINE BABACAR SEYDOU DIEGO SANTINO BENJAMIN THIAGO JHON JHONNY WILSON EDISON
FRANKLIN ROBINSON ANDERSON YEISON DUVAN LUIS NICOLAS CAMILO SEBASTIAN BRAYAN KEVIN ALDO HOMERO
`;

const MUJERES = `
ABRIL ADELA ADELAIDA ADORACION ADRIANA AFRICA AGATA AGUEDA AGUSTINA AINARA AINHOA AINOA AITANA AITZIBER ALAIA ALBA ALEJANDRA
ALEXANDRA ALICIA ALMUDENA AMAIA AMALIA AMAYA AMELIA AMPARO ANA ANABEL ANAIS ANASTASIA ANDREA ANE ANGELA ANGELES ANGELINES
ANNA ANTONIA ANXELA ARANTXA ARANZAZU ARIADNA ARLET ASUNCION AURORA AZUCENA BARBARA BEATRIZ BEGONA BEGOÑA BELEN BERTA
BLANCA BRENDA CANDELA CANDIDA CAROLINA CARLOTA CARME CARMEN CARMINA CASILDA CATALINA CAYETANA CECILIA CELIA CHARO
CHELO CLARA CLAUDIA CONCEPCION CONCHA CONCHI CONCHITA CONSUELO CRISTINA DAFNE DANIELA DEBORA DELIA DIANA DOLORES DOLORS
DULCE EDURNE ELENA ELIANA ELISA ELISABET ELISABETH ELOISA ELVIRA EMILIA EMMA ENCARNA ENCARNACION ENCARNI ESPERANZA
ESTEFANIA ESTHER ESTER ESTIBALIZ ESTRELLA EUGENIA EULALIA EVA FABIOLA FATIMA FATOU FELICIANA FELISA FERNANDA FILOMENA
FLOR FLORENCIA FRANCISCA GARAZI GARBIÑE GARBINE GEMMA GENOVEVA GEORGINA GERTRUDIS GISELA GLORIA GRACIA GRACIELA
GUADALUPE HAIZEA HELENA HERMINIA HORTENSIA IDOIA IDOIA IKERNE ILDEFONSA IMMA INES INGRID INMA INMACULADA IRATXE IRENE
IRIS IRUNE ISABEL ISIDORA ITZIAR IVONNE JACINTA JANA JENNIFER JESICA JESSICA JIMENA JOANA JOSEFA JOSEFINA JUANA JUDIT
JUDITH JULIA JULIANA JUSTINA KARINA KARMELE KATIA LAIA LARA LAURA LEIRE LEONOR LETICIA LIDIA LOLA LOLI LORENA LOURDES
LUCIA LUISA LUZ MACARENA MAGDALENA MAIALEN MAITANE MAITE MANUELA MAR MARGARITA MARGALIDA MARI MARIA MARIANA MARIBEL
MARICARMEN MARINA MARISA MARISOL MARTA MARTINA MATILDE MELANIA MERCE MERCEDES MERITXELL MICAELA MILAGROS MIREIA MIREN
MIRIAM MONICA MONTSE MONTSERRAT MYRIAM NADIA NAHIA NATALIA NATIVIDAD NAYARA NEREA NEUS NIEVES NKECHI NOELIA NOEMI
NORA NURIA OIHANA OLAIA OLGA OLIVIA PALOMA PAOLA PAQUI PATRICIA PAULA PAZ PETRA PIEDAD PILAR PILI PRISCILA PURA
PURIFICACION PURI RAFAELA RAMONA RAQUEL REBECA REMEDIOS REYES ROCIO ROSA ROSALIA ROSANA ROSARIO ROSER ROSI RUT RUTH
SABELA SAMIRA SANDRA SARA SARAI SELENE SHEILA SILVIA SOFIA SOLE SOLEDAD SONIA SUSANA TAMARA TANIA TERESA TRINIDAD UXIA
VALERIA VANESA VANESSA VERONICA VICENTA VICTORIA VIOLETA VIRGINIA XIANA YAIZA YASMINA YOLANDA ZAIRA ZURINE ZORIONE
SIOBHAN PAMELA ANNEGRET BRIGITTE URSULA HEIDI GUACIMARA AYOZE TANAUSU IDAIRA YURENA ATTENERI UXI MARIAJO MAYTE PEPA PEPI MANOLI TERE ROCI NATI FINA ROSI CUCA MARISA MARIPAZ MARILO MAITE MAIDER
OLAYA COVADONGA XANA JOSUNE ARANTZA ARRITXU GARAZI IZASKUN MIRENTXU NEKANE NAIARA UXUE AINTZANE ALAZNE ENARA
SABELA ANTIA IRIA NOA UXIA ALBA XIANA CARME NURIA MERITXELL ROSER MONTSERRAT NEUS LAIA ARLET CLAUDIA
OKSANA IOANA ELENA MARIANA ANDREEA NATALIA IRINA SVETLANA TATIANA OLENA YULIA LI MEIHUA YUTONG XIAOYAN LIN
FATIMA ZAHRA KHADIJA AICHA NAIMA SOUAD MALIKA LATIFA HAYAT HANANE SALMA ASMAE MARIAM AMINATA FATOUMATA AWA
MARYAM NKECHI CHIDINMA ADAEZE ROSA ELVIRA GLADYS JENNY JOHANA YESENIA LEIDY MAYERLI ARACELI GUADALUPE
INGRID ASTRID BRIGITTE HELGA SIGRID EMMA CHLOE SOPHIE CHARLOTTE EMILY OLIVIA HANNAH GIULIA CHIARA FRANCESCA
`;

export const NOMBRES_DE_PILA = new Set(`${HOMBRES} ${MUJERES}`.split(/\s+/).filter(Boolean));

// Nombres que son también palabra corriente, advocación o lugar. Solos, en la duda, pasan.
export const AMBIGUOS = new Set(`
ALBA AMPARO ANGEL ANGELES ASUNCION AURORA AZUCENA BELEN BLANCA CARIDAD CLARA CONCEPCION CONSUELO CRUZ DOLORES DOMINGO
DULCE ENCARNACION ESPERANZA ESTRELLA FATIMA FE FLOR GLORIA GRACIA GUADALUPE INMACULADA IRIS JESUS JUSTO LEON LOURDES LUZ
MAR MARGARITA MARINA MERCEDES MILAGROS MODESTO MONTSERRAT NATIVIDAD NIEVES PALOMA PAZ PIEDAD PILAR PURA PURIFICACION
REMEDIOS REYES ROCIO ROSA ROSARIO SALVADOR SANTIAGO SEGUNDO SOLEDAD TRINIDAD VICTORIA VIOLETA ABRIL AFRICA FLOR
TONO FRANCO GIL URBANO PLACIDO CANDIDO CANDIDA LEAL CESAR NOA LI LIN MAR ALEGRIA JULIO ALEJO MARCO
`.split(/\s+/).filter(Boolean));

// Apellidos chinos frecuentes. En los nombres chinos el apellido va DELANTE («LIN XIAOMING»,
// «Wang Li Na»), así que la regla del nombre de pila no los ve.
export const APELLIDOS_CHINOS = new Set(`
WANG LI ZHANG LIU CHEN YANG HUANG ZHAO WU ZHOU XU SUN MA ZHU HU GUO HE LIN GAO LUO ZHENG LIANG XIE SONG TANG HAN
FENG DENG CAO PENG ZENG XIAO TIAN DONG PAN YUAN CAI JIANG YU DU YE CHENG WEI SU LU DING REN SHEN YAO LU JIN QIAN
ZHONG TAN WAN HUA QIU LAI FANG KONG CUI YIN MAO JIA XIA GU HOU SHAO MENG LONG WAN DUAN LEI QIAN TANG YAN
`.split(/\s+/).filter(Boolean));

export default NOMBRES_DE_PILA;
